<?php

namespace App\Services;

final class EventCatalog
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public function all(): array
    {
        return array_values($this->records());
    }

    /**
     * @return array<string, mixed>|null
     */
    public function find(string $key): ?array
    {
        return $this->records()[$key] ?? null;
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    private function records(): array
    {
        return [
            'small-dog-social' => [
                'key' => 'small-dog-social',
                'title' => __('messages.calm_walk_at_laurelhurst_park'),
                'short_description' => __('messages.a_host_guided_parallel_walk_with_calm_arrivals_and_no_off_leash_play'),
                'description' => __('messages.a_low_pressure_neighborhood_walk_for_medium_and_larger_dogs_who_do_best_with_space_we_begin_with_parallel_movement_keep_every_dog_on_leash_and_share_the_exact'),
                'category' => __('messages.walk'),
                'event_type' => 'group-walk',
                'format' => 'offline',
                'privacy' => 'closed',
                'registration_policy' => 'approval',
                'status' => 'registration_open',
                'starts_at' => '2026-08-01T10:00:00-07:00',
                'ends_at' => '2026-08-01T11:30:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.laurelhurst_park_southeast_portland'),
                'exact_location' => __('messages.se_ankeny_entrance_beside_the_covered_picnic_tables'),
                'online_link' => null,
                'distance' => __('messages.1_2_mi'),
                'capacity' => 8,
                'base_attendees' => 6,
                'waitlist_count' => 1,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.medium_or_large_dogs_leash_required_calm_introductions'),
                'activity_level' => __('messages.calm'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.community_hosts'),
                'organizer_type' => __('messages.community'),
                'organizer_initials' => 'CH',
                'verification_label' => null,
                'managed_by_current_user' => false,
                'language' => __('messages.english'),
                'image' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.two_dogs_walking_side_by_side_on_a_tree_lined_path'),
                'tags' => [__('messages.parallel_walk'), __('messages.calm_pace'), __('messages.leash_required_lowercase')],
                'recommendation_reason' => __('messages.shared_routines'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.mild_with_light_cloud'),
                    'temperature' => '68°F',
                    'advisory' => __('messages.bring_individual_water_and_expect_damp_grass'),
                    'tone' => 'safe',
                ],
            ],
            'puppy-social-lab' => [
                'key' => 'puppy-social-lab',
                'title' => __('messages.puppy_socialization_lab'),
                'short_description' => __('messages.small_supervised_groups_breaks_and_careful_first_experiences'),
                'description' => __('messages.a_practical_socialization_session_for_young_dogs_with_structured_observation_short_exercises_and_rest_one_meeting_cannot_complete_socialization_so_the_trainer'),
                'category' => __('messages.training'),
                'event_type' => 'puppy-training',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'approval',
                'status' => 'few_spots',
                'starts_at' => '2026-08-02T09:30:00-07:00',
                'ends_at' => '2026-08-02T10:30:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.rose_city_training_hall_buckman'),
                'exact_location' => __('messages.studio_b_815_se_belmont_street'),
                'online_link' => null,
                'distance' => __('messages.2_4_mi'),
                'capacity' => 6,
                'base_attendees' => 5,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.puppies_12_24_weeks_vaccination_status_reviewed_privately'),
                'activity_level' => __('messages.moderate'),
                'ticket_model' => 'paid',
                'price_minor' => 3500,
                'currency' => 'USD',
                'organizer' => __('messages.ari_jensen'),
                'organizer_type' => __('messages.verified_trainer'),
                'organizer_initials' => 'AJ',
                'verification_label' => __('messages.professional_qualification_verified'),
                'managed_by_current_user' => false,
                'language' => __('messages.english'),
                'image' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.young_golden_retriever_sitting_outside_during_a_training_break'),
                'tags' => ['puppies', __('messages.trainer_led'), __('messages.small_group')],
                'recommendation_reason' => __('messages.a_verified_trainer_near_your_saved_neighborhood'),
                'commercial_label' => __('messages.paid_event'),
                'weather' => [
                    'summary' => __('messages.indoor_event'),
                    'temperature' => __('messages.climate_controlled'),
                    'advisory' => __('messages.arrive_ten_minutes_early_for_a_calm_entry'),
                    'tone' => 'safe',
                ],
            ],
            'beginner-training-series' => [
                'key' => 'beginner-training-series',
                'title' => __('messages.foundations_training_course'),
                'short_description' => __('messages.four_beginner_sessions_covering_attention_recall_waiting_and_leash_skills'),
                'description' => __('messages.a_four_session_foundation_course_with_one_check_in_per_class_take_home_material_and_an_owner_chat_attendance_confirms_participation_only_and_does_not_grant_a'),
                'category' => __('messages.training'),
                'event_type' => 'training-course',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-08T11:00:00-07:00',
                'ends_at' => '2026-08-08T12:15:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.sellwood_community_hall'),
                'exact_location' => __('messages.room_204_1436_se_spokane_street'),
                'online_link' => null,
                'distance' => __('messages.3_1_mi'),
                'capacity' => 6,
                'base_attendees' => 3,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.beginner_dogs_fixed_leash_one_responsible_handler'),
                'activity_level' => __('messages.moderate'),
                'ticket_model' => 'paid',
                'price_minor' => 12000,
                'currency' => 'USD',
                'organizer' => __('messages.ari_jensen'),
                'organizer_type' => __('messages.verified_trainer'),
                'organizer_initials' => 'AJ',
                'verification_label' => __('messages.professional_qualification_verified'),
                'managed_by_current_user' => false,
                'language' => __('messages.english'),
                'image' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.dog_looking_toward_a_handler_during_a_focused_training_session'),
                'tags' => [__('messages.beginner_course'), __('messages.four_sessions'), __('messages.materials_included')],
                'recommendation_reason' => __('messages.you_saved_beginner_training_posts_recently'),
                'commercial_label' => __('messages.paid_course'),
                'weather' => [
                    'summary' => __('messages.indoor_event'),
                    'temperature' => __('messages.climate_controlled'),
                    'advisory' => __('messages.a_quiet_waiting_area_is_available_near_the_side_entrance'),
                    'tone' => 'safe',
                ],
            ],
            'rose-city-pet-show' => [
                'key' => 'rose-city-pet-show',
                'title' => __('messages.rose_city_companion_show'),
                'short_description' => __('messages.verified_show_schedule_categories_document_guidance_and_quiet_zones'),
                'description' => __('messages.a_club_run_companion_show_with_category_schedules_veterinary_control_accessible_seating_quiet_preparation_areas_and_individual_qr_check_in'),
                'category' => __('messages.show'),
                'event_type' => 'pet-show',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'approval',
                'status' => 'registration_open',
                'starts_at' => '2026-08-15T08:00:00-07:00',
                'ends_at' => '2026-08-15T18:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.portland_expo_center'),
                'exact_location' => __('messages.hall_d_exhibitor_entrance_on_marine_drive'),
                'online_link' => null,
                'distance' => __('messages.7_8_mi'),
                'capacity' => 120,
                'base_attendees' => 82,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 2,
                'pet_requirements' => __('messages.registered_category_and_privately_reviewed_documents'),
                'activity_level' => __('messages.variable'),
                'ticket_model' => 'paid',
                'price_minor' => 4500,
                'currency' => 'USD',
                'organizer' => __('messages.rose_city_companion_club'),
                'organizer_type' => __('messages.verified_organization'),
                'organizer_initials' => 'RC',
                'verification_label' => __('messages.organization_and_venue_verified'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_spanish'),
                'image' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.dog_standing_calmly_at_a_public_companion_event'),
                'tags' => ['show', __('messages.verified_venue'), __('messages.quiet_zone_lowercase')],
                'recommendation_reason' => __('messages.a_verified_event_followed_by_your_local_groups'),
                'commercial_label' => __('messages.paid_event'),
                'weather' => [
                    'summary' => __('messages.indoor_event'),
                    'temperature' => __('messages.climate_controlled'),
                    'advisory' => __('messages.use_the_exhibitor_entrance_shown_after_approval'),
                    'tone' => 'safe',
                ],
            ],
            'shelter-open-house' => [
                'key' => 'shelter-open-house',
                'title' => __('messages.shelter_open_house_and_adoption_day'),
                'short_description' => __('messages.meet_adoptable_pets_learn_about_fostering_and_tour_the_shelter_safely'),
                'description' => __('messages.a_verified_shelter_day_with_timed_introductions_volunteer_orientation_supply_collection_and_clear_rules_about_bringing_resident_pets'),
                'category' => __('messages.adoption'),
                'event_type' => 'adoption-day',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-09T12:00:00-07:00',
                'ends_at' => '2026-08-09T16:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.rose_city_animal_aid_north_portland'),
                'exact_location' => __('messages.visitor_entrance_2050_n_columbia_boulevard'),
                'online_link' => null,
                'distance' => __('messages.5_6_mi'),
                'capacity' => 60,
                'base_attendees' => 34,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => __('messages.owners_attend_without_resident_pets'),
                'activity_level' => __('messages.easy'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.rose_city_animal_aid'),
                'organizer_type' => __('messages.verified_shelter'),
                'organizer_initials' => 'RA',
                'verification_label' => __('messages.shelter_verified'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_spanish'),
                'image' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.shelter_dog_resting_safely_on_a_blue_couch'),
                'tags' => ['adoption', 'fostering', __('messages.without_resident_pets')],
                'recommendation_reason' => __('messages.you_follow_local_adoption_and_foster_topics'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.mostly_indoors'),
                    'temperature' => '70°F',
                    'advisory' => __('messages.the_tour_includes_a_short_covered_outdoor_section'),
                    'tone' => 'safe',
                ],
            ],
            'missing-pet-search' => [
                'key' => 'missing-pet-search',
                'title' => __('messages.search_action'),
                'short_description' => __('messages.coordinated_volunteer_search_with_assigned_zones_and_safe_sighting_instructions'),
                'description' => __('messages.a_time_sensitive_search_action_volunteers_receive_a_public_meeting_point_a_zone_and_instructions_not_to_chase_or_publicly_share_private_resident_details'),
                'category' => __('messages.search_action'),
                'event_type' => 'search-action',
                'format' => 'offline',
                'privacy' => 'closed',
                'registration_policy' => 'approval',
                'status' => 'urgent',
                'starts_at' => '2026-07-30T18:00:00-07:00',
                'ends_at' => '2026-07-30T21:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.alberta_arts_district'),
                'exact_location' => __('messages.volunteer_desk_at_alberta_park_west_entrance'),
                'online_link' => null,
                'distance' => __('messages.2_0_mi'),
                'capacity' => 40,
                'base_attendees' => 22,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => __('messages.volunteers_attend_without_pets'),
                'activity_level' => __('messages.moderate'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.community_hosts'),
                'organizer_type' => __('messages.community'),
                'organizer_initials' => 'CH',
                'verification_label' => __('messages.lost_pet_alert_confirmed'),
                'managed_by_current_user' => false,
                'language' => __('messages.english'),
                'image' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.brown_dog_looking_toward_the_camera_in_a_grassy_area'),
                'tags' => ['urgent', 'volunteers', __('messages.do_not_chase')],
                'recommendation_reason' => __('messages.urgent_verified_alert_in_your_nearby_area'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.clear_evening'),
                    'temperature' => '65°F',
                    'advisory' => __('messages.bring_a_charged_phone_and_reflective_outer_layer'),
                    'tone' => 'attention',
                ],
            ],
            'baxter-birthday' => [
                'key' => 'baxter-birthday',
                'title' => __('messages.baxter_s_quiet_birthday_picnic'),
                'short_description' => __('messages.a_private_celebration_for_close_pet_friends_and_their_owners'),
                'description' => __('messages.a_small_invitation_only_picnic_with_a_quiet_rest_zone_pre_agreed_food_rules_and_a_private_shared_album_after_the_event'),
                'category' => __('messages.celebration'),
                'event_type' => 'private-celebration',
                'format' => 'offline',
                'privacy' => 'hidden',
                'registration_policy' => 'invitation',
                'status' => 'registration_open',
                'starts_at' => '2026-08-16T15:00:00-07:00',
                'ends_at' => '2026-08-16T17:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.private_garden_portland'),
                'exact_location' => __('messages.shared_only_with_accepted_guests'),
                'online_link' => null,
                'distance' => __('messages.private'),
                'capacity' => 10,
                'base_attendees' => 7,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.invited_pet_friends_only_food_agreed_in_advance'),
                'activity_level' => __('messages.calm'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.jamie_cho'),
                'organizer_type' => __('messages.owner'),
                'organizer_initials' => 'JC',
                'verification_label' => null,
                'managed_by_current_user' => false,
                'language' => __('messages.english'),
                'image' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.dog_wearing_a_birthday_hat_at_a_small_celebration'),
                'tags' => ['private', __('messages.quiet_zone_lowercase'), __('messages.friends_only')],
                'recommendation_reason' => __('messages.shared_routines'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.warm_afternoon'),
                    'temperature' => '74°F',
                    'advisory' => __('messages.shade_and_a_quiet_indoor_room_are_available'),
                    'tone' => 'safe',
                ],
            ],
            'travel-ready-webinar' => [
                'key' => 'travel-ready-webinar',
                'title' => __('messages.travel_ready_pet_webinar'),
                'short_description' => __('messages.verified_veterinary_guidance_for_carriers_documents_routines_and_travel_planning'),
                'description' => __('messages.a_live_webinar_with_moderated_questions_timezone_aware_reminders_protected_access_captions_a_recording_slides_and_cited_resources_the_presenter_does_not'),
                'category' => __('messages.webinar'),
                'event_type' => 'expert-webinar',
                'format' => 'online',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-06T18:00:00-07:00',
                'ends_at' => '2026-08-06T19:15:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.online'),
                'exact_location' => __('messages.online_room_opens_15_minutes_before_the_webinar'),
                'online_link' => 'https://events.example.test/travel-ready',
                'distance' => __('messages.online'),
                'capacity' => 250,
                'base_attendees' => 146,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => __('messages.owners_may_attend_without_pets'),
                'activity_level' => __('messages.lecture'),
                'ticket_model' => 'paid',
                'price_minor' => 1800,
                'currency' => 'USD',
                'organizer' => __('messages.dr_elena_park'),
                'organizer_type' => __('messages.verified_veterinarian'),
                'organizer_initials' => 'EP',
                'verification_label' => __('messages.veterinary_profession_verified'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_captions_available'),
                'image' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.veterinarian_speaking_with_a_pet_owner_beside_a_dog'),
                'tags' => ['online', 'veterinarian', __('messages.recording_included')],
                'recommendation_reason' => __('messages.shared_routines'),
                'commercial_label' => __('messages.paid_webinar'),
                'weather' => [
                    'summary' => __('messages.online_event'),
                    'temperature' => __('messages.join_from_home'),
                    'advisory' => __('messages.test_audio_and_captions_before_the_room_opens'),
                    'tone' => 'safe',
                ],
            ],
        ];
    }
}
