<?php

namespace App\Services;

final class EventCatalog
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public function all(): array
    {
        return array_values($this->records());
    }

    /**
     * @return array<string, mixed>|null
     */
    public function find(string $key): ?array
    {
        return $this->records()[$key] ?? null;
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    private function records(): array
    {
        return [
            'small-dog-social' => [
                'key' => 'small-dog-social',
                'title' => __('messages.calm_walk_at_laurelhurst_park_7bedc16263'),
                'short_description' => __('messages.a_host_guided_parallel_walk_with_calm_arrivals_and_no_of_591e7ba603'),
                'description' => __('messages.a_low_pressure_neighborhood_walk_for_medium_and_larger_d_6dca08d8be'),
                'category' => __('messages.walk_08ee52ae12'),
                'event_type' => 'group-walk',
                'format' => 'offline',
                'privacy' => 'closed',
                'registration_policy' => 'approval',
                'status' => 'registration_open',
                'starts_at' => '2026-08-01T10:00:00-07:00',
                'ends_at' => '2026-08-01T11:30:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.laurelhurst_park_southeast_portland_ad3eeeac45'),
                'exact_location' => __('messages.se_ankeny_entrance_beside_the_covered_picnic_tables_9ab72f2eaf'),
                'online_link' => null,
                'distance' => __('messages.1_2_mi_7aa05aea3a'),
                'capacity' => 8,
                'base_attendees' => 6,
                'waitlist_count' => 1,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.medium_or_large_dogs_leash_required_calm_introductions_9c0156885e'),
                'activity_level' => __('messages.calm_38f6b83e2d'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.mia_carter_0e5b29cc3b'),
                'organizer_type' => __('messages.owner_4b1b8aa360'),
                'organizer_initials' => 'MC',
                'verification_label' => null,
                'managed_by_current_user' => true,
                'language' => __('messages.english_ba118bf7fc'),
                'image' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.two_dogs_walking_side_by_side_on_a_tree_lined_path_6abb9377f2'),
                'tags' => [__('messages.parallel_walk_6ced82c5ce'), __('messages.calm_pace_f8e1681acb'), __('messages.leash_required_7b6dc26c33')],
                'recommendation_reason' => __('messages.matches_scout_s_size_and_your_interest_in_calm_local_wal_1cf99bb602'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.mild_with_light_cloud_d3f43435e6'),
                    'temperature' => '68°F',
                    'advisory' => __('messages.bring_individual_water_and_expect_damp_grass_d51e7b0d7c'),
                    'tone' => 'safe',
                ],
            ],
            'puppy-social-lab' => [
                'key' => 'puppy-social-lab',
                'title' => __('messages.puppy_socialization_lab_3f601ed1c2'),
                'short_description' => __('messages.small_supervised_groups_breaks_and_careful_first_experie_fad18f0eef'),
                'description' => __('messages.a_practical_socialization_session_for_young_dogs_with_st_6b26bee8d5'),
                'category' => __('messages.training_36a798e3f3'),
                'event_type' => 'puppy-training',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'approval',
                'status' => 'few_spots',
                'starts_at' => '2026-08-02T09:30:00-07:00',
                'ends_at' => '2026-08-02T10:30:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.rose_city_training_hall_buckman_db6ef215b2'),
                'exact_location' => __('messages.studio_b_815_se_belmont_street_d2bc25cdd7'),
                'online_link' => null,
                'distance' => __('messages.2_4_mi_22afe13d12'),
                'capacity' => 6,
                'base_attendees' => 5,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.puppies_12_24_weeks_vaccination_status_reviewed_privatel_43ecc86b5d'),
                'activity_level' => __('messages.moderate_5c42afc7a2'),
                'ticket_model' => 'paid',
                'price_minor' => 3500,
                'currency' => 'USD',
                'organizer' => __('messages.ari_jensen_6c670df410'),
                'organizer_type' => __('messages.verified_trainer_adc950c999'),
                'organizer_initials' => 'AJ',
                'verification_label' => __('messages.professional_qualification_verified_c8ad1d8ed6'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_ba118bf7fc'),
                'image' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.young_golden_retriever_sitting_outside_during_a_training_e588f601b5'),
                'tags' => ['puppies', __('messages.trainer_led_f26344c9ae'), __('messages.small_group_84f126d8e9')],
                'recommendation_reason' => __('messages.a_verified_trainer_near_your_saved_neighborhood_8336ee56b4'),
                'commercial_label' => __('messages.paid_event_53d5044b4e'),
                'weather' => [
                    'summary' => __('messages.indoor_event_16ba3d59ff'),
                    'temperature' => __('messages.climate_controlled_74cc1aeb15'),
                    'advisory' => __('messages.arrive_ten_minutes_early_for_a_calm_entry_d36b97a0c0'),
                    'tone' => 'safe',
                ],
            ],
            'beginner-training-series' => [
                'key' => 'beginner-training-series',
                'title' => __('messages.foundations_training_course_75854b65f9'),
                'short_description' => __('messages.four_beginner_sessions_covering_attention_recall_waiting_246659fee9'),
                'description' => __('messages.a_four_session_foundation_course_with_one_check_in_per_c_7ea1f0fec3'),
                'category' => __('messages.training_36a798e3f3'),
                'event_type' => 'training-course',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-08T11:00:00-07:00',
                'ends_at' => '2026-08-08T12:15:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.sellwood_community_hall_61f6436005'),
                'exact_location' => __('messages.room_204_1436_se_spokane_street_7f9b3281a4'),
                'online_link' => null,
                'distance' => __('messages.3_1_mi_d22fd52438'),
                'capacity' => 6,
                'base_attendees' => 3,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.beginner_dogs_fixed_leash_one_responsible_handler_36d6e437d6'),
                'activity_level' => __('messages.moderate_5c42afc7a2'),
                'ticket_model' => 'paid',
                'price_minor' => 12000,
                'currency' => 'USD',
                'organizer' => __('messages.ari_jensen_6c670df410'),
                'organizer_type' => __('messages.verified_trainer_adc950c999'),
                'organizer_initials' => 'AJ',
                'verification_label' => __('messages.professional_qualification_verified_c8ad1d8ed6'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_ba118bf7fc'),
                'image' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.dog_looking_toward_a_handler_during_a_focused_training_s_6beb589b34'),
                'tags' => [__('messages.beginner_course_f0f3a00c19'), __('messages.four_sessions_60124f4bb8'), __('messages.materials_included_d9bdec6d35')],
                'recommendation_reason' => __('messages.you_saved_beginner_training_posts_recently_0dd4335794'),
                'commercial_label' => __('messages.paid_course_a5ca3de52e'),
                'weather' => [
                    'summary' => __('messages.indoor_event_16ba3d59ff'),
                    'temperature' => __('messages.climate_controlled_74cc1aeb15'),
                    'advisory' => __('messages.a_quiet_waiting_area_is_available_near_the_side_entrance_ffdf0e0db2'),
                    'tone' => 'safe',
                ],
            ],
            'rose-city-pet-show' => [
                'key' => 'rose-city-pet-show',
                'title' => __('messages.rose_city_companion_show_821a636d26'),
                'short_description' => __('messages.verified_show_schedule_categories_document_guidance_and__bf5d766487'),
                'description' => __('messages.a_club_run_companion_show_with_category_schedules_veteri_f219501aa2'),
                'category' => __('messages.show_0df6f1cad3'),
                'event_type' => 'pet-show',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'approval',
                'status' => 'registration_open',
                'starts_at' => '2026-08-15T08:00:00-07:00',
                'ends_at' => '2026-08-15T18:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.portland_expo_center_88e2df6f5a'),
                'exact_location' => __('messages.hall_d_exhibitor_entrance_on_marine_drive_0d4e6e0831'),
                'online_link' => null,
                'distance' => __('messages.7_8_mi_9a1b33d9f3'),
                'capacity' => 120,
                'base_attendees' => 82,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 2,
                'pet_requirements' => __('messages.registered_category_and_privately_reviewed_documents_e3b86d7ee1'),
                'activity_level' => __('messages.variable_e57e998726'),
                'ticket_model' => 'paid',
                'price_minor' => 4500,
                'currency' => 'USD',
                'organizer' => __('messages.rose_city_companion_club_9ef46f27ae'),
                'organizer_type' => __('messages.verified_organization_bb7ed4c3c5'),
                'organizer_initials' => 'RC',
                'verification_label' => __('messages.organization_and_venue_verified_ae2cf257e0'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_spanish_b50c1cd84d'),
                'image' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.dog_standing_calmly_at_a_public_companion_event_e412527f7a'),
                'tags' => ['show', __('messages.verified_venue_e6cd58a2ea'), __('messages.quiet_zone_c1e15d55df')],
                'recommendation_reason' => __('messages.a_verified_event_followed_by_your_local_groups_87b976daed'),
                'commercial_label' => __('messages.paid_event_53d5044b4e'),
                'weather' => [
                    'summary' => __('messages.indoor_event_16ba3d59ff'),
                    'temperature' => __('messages.climate_controlled_74cc1aeb15'),
                    'advisory' => __('messages.use_the_exhibitor_entrance_shown_after_approval_87d87bf650'),
                    'tone' => 'safe',
                ],
            ],
            'shelter-open-house' => [
                'key' => 'shelter-open-house',
                'title' => __('messages.shelter_open_house_and_adoption_day_d29233fae8'),
                'short_description' => __('messages.meet_adoptable_pets_learn_about_fostering_and_tour_the_s_089f9a5fda'),
                'description' => __('messages.a_verified_shelter_day_with_timed_introductions_voluntee_82512a45e2'),
                'category' => __('messages.adoption_9b33128339'),
                'event_type' => 'adoption-day',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-09T12:00:00-07:00',
                'ends_at' => '2026-08-09T16:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.rose_city_animal_aid_north_portland_ca3ab321ea'),
                'exact_location' => __('messages.visitor_entrance_2050_n_columbia_boulevard_1b5e8a405a'),
                'online_link' => null,
                'distance' => __('messages.5_6_mi_7c1427fdf6'),
                'capacity' => 60,
                'base_attendees' => 34,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => __('messages.owners_attend_without_resident_pets_de8dc7ac92'),
                'activity_level' => __('messages.easy_d6915875de'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.rose_city_animal_aid_0ae16a6b88'),
                'organizer_type' => __('messages.verified_shelter_52247645ed'),
                'organizer_initials' => 'RA',
                'verification_label' => __('messages.shelter_verified_8b5018b2dd'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_spanish_b50c1cd84d'),
                'image' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.shelter_dog_resting_safely_on_a_blue_couch_d0e4f36976'),
                'tags' => ['adoption', 'fostering', __('messages.without_resident_pets_7246f282d9')],
                'recommendation_reason' => __('messages.you_follow_local_adoption_and_foster_topics_a7e80d9bc2'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.mostly_indoors_7e40ae1818'),
                    'temperature' => '70°F',
                    'advisory' => __('messages.the_tour_includes_a_short_covered_outdoor_section_a166805ad8'),
                    'tone' => 'safe',
                ],
            ],
            'missing-scout-search' => [
                'key' => 'missing-scout-search',
                'title' => __('messages.urgent_neighborhood_search_for_scout_c50db9c424'),
                'short_description' => __('messages.coordinated_volunteer_search_with_assigned_zones_and_saf_e3adc5303a'),
                'description' => __('messages.a_time_sensitive_search_action_volunteers_receive_a_publ_f8b6212240'),
                'category' => __('messages.search_action_876eb67a42'),
                'event_type' => 'search-action',
                'format' => 'offline',
                'privacy' => 'closed',
                'registration_policy' => 'approval',
                'status' => 'urgent',
                'starts_at' => '2026-07-30T18:00:00-07:00',
                'ends_at' => '2026-07-30T21:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.alberta_arts_district_ec01c06446'),
                'exact_location' => __('messages.volunteer_desk_at_alberta_park_west_entrance_601e3a177f'),
                'online_link' => null,
                'distance' => __('messages.2_0_mi_1f3dc2532a'),
                'capacity' => 40,
                'base_attendees' => 22,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => __('messages.volunteers_attend_without_pets_0cb0a5a77c'),
                'activity_level' => __('messages.moderate_5c42afc7a2'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.mia_carter_0e5b29cc3b'),
                'organizer_type' => __('messages.owner_and_search_coordinator_e38491528f'),
                'organizer_initials' => 'MC',
                'verification_label' => __('messages.lost_pet_alert_confirmed_fe3364036d'),
                'managed_by_current_user' => true,
                'language' => __('messages.english_ba118bf7fc'),
                'image' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.brown_dog_looking_toward_the_camera_in_a_grassy_area_85d847d142'),
                'tags' => ['urgent', 'volunteers', __('messages.do_not_chase_7493e2cda7')],
                'recommendation_reason' => __('messages.urgent_verified_alert_in_your_nearby_area_57f91d1b19'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.clear_evening_121661c82a'),
                    'temperature' => '65°F',
                    'advisory' => __('messages.bring_a_charged_phone_and_reflective_outer_layer_3ae2f02e31'),
                    'tone' => 'attention',
                ],
            ],
            'baxter-birthday' => [
                'key' => 'baxter-birthday',
                'title' => __('messages.baxter_s_quiet_birthday_picnic_6375ba8c0a'),
                'short_description' => __('messages.a_private_celebration_for_close_pet_friends_and_their_ow_f9c06225a3'),
                'description' => __('messages.a_small_invitation_only_picnic_with_a_quiet_rest_zone_pr_923a464d7c'),
                'category' => __('messages.celebration_4a8b403035'),
                'event_type' => 'private-celebration',
                'format' => 'offline',
                'privacy' => 'hidden',
                'registration_policy' => 'invitation',
                'status' => 'registration_open',
                'starts_at' => '2026-08-16T15:00:00-07:00',
                'ends_at' => '2026-08-16T17:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.private_garden_portland_78d363089d'),
                'exact_location' => __('messages.shared_only_with_accepted_guests_c7dc70f2c3'),
                'online_link' => null,
                'distance' => __('messages.private_c63eb6720c'),
                'capacity' => 10,
                'base_attendees' => 7,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => __('messages.invited_pet_friends_only_food_agreed_in_advance_6ea1a7f8ae'),
                'activity_level' => __('messages.calm_38f6b83e2d'),
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => __('messages.jamie_cho_5f313c129b'),
                'organizer_type' => __('messages.owner_4b1b8aa360'),
                'organizer_initials' => 'JC',
                'verification_label' => null,
                'managed_by_current_user' => false,
                'language' => __('messages.english_ba118bf7fc'),
                'image' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.dog_wearing_a_birthday_hat_at_a_small_celebration_ffa2b8a6f0'),
                'tags' => ['private', __('messages.quiet_zone_c1e15d55df'), __('messages.friends_only_d4bccdb229')],
                'recommendation_reason' => __('messages.invited_through_scout_s_close_pet_circle_4109b649bd'),
                'commercial_label' => null,
                'weather' => [
                    'summary' => __('messages.warm_afternoon_5561f09430'),
                    'temperature' => '74°F',
                    'advisory' => __('messages.shade_and_a_quiet_indoor_room_are_available_452f3281e3'),
                    'tone' => 'safe',
                ],
            ],
            'travel-ready-webinar' => [
                'key' => 'travel-ready-webinar',
                'title' => __('messages.travel_ready_pet_webinar_8982da150f'),
                'short_description' => __('messages.verified_veterinary_guidance_for_carriers_documents_rout_918249bcce'),
                'description' => __('messages.a_live_webinar_with_moderated_questions_timezone_aware_r_f03fae0407'),
                'category' => __('messages.webinar_83584124b5'),
                'event_type' => 'expert-webinar',
                'format' => 'online',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-06T18:00:00-07:00',
                'ends_at' => '2026-08-06T19:15:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => __('messages.online_0d21bd5202'),
                'exact_location' => __('messages.online_room_opens_15_minutes_before_the_webinar_00da5c50f2'),
                'online_link' => 'https://events.example.test/travel-ready',
                'distance' => __('messages.online_0d21bd5202'),
                'capacity' => 250,
                'base_attendees' => 146,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => __('messages.owners_may_attend_without_pets_d0f395d9f5'),
                'activity_level' => __('messages.lecture_a757c6b403'),
                'ticket_model' => 'paid',
                'price_minor' => 1800,
                'currency' => 'USD',
                'organizer' => __('messages.dr_elena_park_4db101e23c'),
                'organizer_type' => __('messages.verified_veterinarian_30ade68387'),
                'organizer_initials' => 'EP',
                'verification_label' => __('messages.veterinary_profession_verified_32de0fea35'),
                'managed_by_current_user' => false,
                'language' => __('messages.english_captions_available_f8e8880f22'),
                'image' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => __('messages.veterinarian_speaking_with_a_pet_owner_beside_a_dog_928df6b29c'),
                'tags' => ['online', 'veterinarian', __('messages.recording_included_f712494e5b')],
                'recommendation_reason' => __('messages.you_saved_travel_planning_guides_for_scout_474d8a02e9'),
                'commercial_label' => __('messages.paid_webinar_6ff0bd4dd3'),
                'weather' => [
                    'summary' => __('messages.online_event_63540fba45'),
                    'temperature' => __('messages.join_from_home_bf9a739902'),
                    'advisory' => __('messages.test_audio_and_captions_before_the_room_opens_d0362c529a'),
                    'tone' => 'safe',
                ],
            ],
        ];
    }
}
