<?php

namespace App\Services;

final class PawCirclePlaceCatalog
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public function all(): array
    {
        return array_values($this->records());
    }

    /**
     * @return array<string, mixed>|null
     */
    public function find(string $key): ?array
    {
        return $this->records()[$key] ?? null;
    }

    /**
     * @return array<string, string>
     */
    public function categoryOptions(): array
    {
        return [
            'all' => 'All places',
            'park' => 'Parks',
            'dog-park' => 'Dog parks',
            'route' => 'Walking routes',
            'vet' => 'Veterinary clinics',
            'emergency-vet' => '24-hour clinics',
            'pet-store' => 'Pet stores',
            'grooming' => 'Grooming',
            'shelter' => 'Shelters',
            'pet-cafe' => 'Pet-friendly cafes',
        ];
    }

    /**
     * @return array<string, string>
     */
    public function speciesOptions(): array
    {
        return [
            'any' => 'Any pet',
            'dog' => 'Dogs',
            'cat' => 'Cats',
            'bird' => 'Birds',
            'rabbit' => 'Rabbits',
            'rodent' => 'Small mammals',
            'reptile' => 'Reptiles',
            'exotic' => 'Exotic pets',
        ];
    }

    /**
     * @return array<string, string>
     */
    public function sizeOptions(): array
    {
        return [
            'any' => 'Any size',
            'very-small' => 'Very small',
            'small' => 'Small',
            'medium' => 'Medium',
            'large' => 'Large',
            'very-large' => 'Very large',
        ];
    }

    /**
     * @return array<string, string>
     */
    public function iconOptions(): array
    {
        return [
            'park' => 'trees',
            'dog-park' => 'fence',
            'route' => 'route',
            'vet' => 'stethoscope',
            'emergency-vet' => 'siren',
            'pet-store' => 'shopping-bag',
            'grooming' => 'scissors',
            'shelter' => 'house-heart',
            'pet-cafe' => 'coffee',
        ];
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    private function records(): array
    {
        $dogSizes = ['very-small', 'small', 'medium', 'large', 'very-large'];
        $commonPets = ['dog', 'cat'];
        $allCompanions = ['dog', 'cat', 'bird', 'rabbit', 'rodent', 'reptile', 'exotic'];

        return [
            'vingis-quiet-loop' => [
                'key' => 'vingis-quiet-loop',
                'name' => 'Vingis Park quiet loop',
                'short_name' => 'Vingis Park',
                'primary_category' => 'park',
                'categories' => ['park', 'route'],
                'category_label' => 'Park and walking route',
                'category_icon' => 'trees',
                'summary' => 'A broad, tree-lined loop with calmer outer paths, water points, and room for parallel walking.',
                'city' => 'Vilnius',
                'neighborhood' => 'Naujamiestis',
                'address' => 'M. K. Čiurlionio g. 100, Vilnius',
                'general_location' => 'Vingis Park · western entrances',
                'latitude' => 54.6834,
                'longitude' => 25.2368,
                'map_x' => 38,
                'map_y' => 45,
                'coordinate_accuracy' => 'Main public entrance',
                'distance_km' => 3.8,
                'travel_minutes' => 14,
                'open_state' => 'open',
                'open_label' => 'Open now',
                'closes_at' => 'Open all day',
                'hours_summary' => 'Public paths open all day; lighting varies by entrance',
                'special_hours' => 'Event closures are posted as temporary updates.',
                'phone' => null,
                'website' => 'https://vilnius.lt/',
                'email' => null,
                'accepted_species' => ['dog'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Leash required outside signed off-leash areas',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'free',
                'crowd_level' => 'medium',
                'crowd_label' => 'Usually calmer before 9:00 AM and after 8:00 PM',
                'noise_level' => 'Mixed; quieter on the western loop',
                'rules' => [
                    'Keep pets leashed outside signed areas.',
                    'Use extra distance near cyclists and event crowds.',
                    'Group events must respect municipal park rules.',
                ],
                'features' => ['wide paths', 'water', 'shade', 'benches', 'bins', 'evening lighting'],
                'accessibility' => ['step-free routes', 'wide paths', 'accessible parking', 'rest areas'],
                'safety' => ['separate from main roads', 'several early exit points', 'nearby public transport'],
                'services' => ['4.6 km quiet loop', '2.1 km shortcut', 'water points', 'event meeting areas'],
                'pricing' => ['Park access' => 'Free'],
                'rating' => 4.7,
                'review_count' => 184,
                'verified_review_count' => 61,
                'verification' => [
                    'label' => 'Rules checked from a public source',
                    'scope' => 'Address and general park rules',
                    'updated_at' => '2026-07-27',
                    'tone' => 'verified',
                ],
                'data_freshness' => 'Community conditions checked 2 hours ago',
                'recommendation_reason' => 'Best match for a calm evening walk with Scout',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => false,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Broad shaded path through a green city park',
                'route' => [
                    'distance' => '4.6 km',
                    'duration' => '65–85 min',
                    'difficulty' => 'Easy',
                    'surface' => 'Paved and compact gravel',
                    'elevation' => 'Mostly level',
                    'shortcuts' => ['2.1 km riverside return', 'bus stop exit after 3 km'],
                    'hazards' => ['busy cycle crossing near the main avenue', 'mud on unpaved edges after rain'],
                    'home_privacy' => 'Starts at a public park entrance; no home point is stored.',
                ],
                'events' => ['small-dog-social'],
                'base_warnings' => [],
            ],
            'bernardine-evening-park' => [
                'key' => 'bernardine-evening-park',
                'name' => 'Bernardine Garden evening paths',
                'short_name' => 'Bernardine Garden',
                'primary_category' => 'park',
                'categories' => ['park'],
                'category_label' => 'City park',
                'category_icon' => 'trees',
                'summary' => 'A central, well-lit garden with smooth paths and easy transit, but more visitors and no dedicated dog water.',
                'city' => 'Vilnius',
                'neighborhood' => 'Old Town',
                'address' => 'B. Radvilaitės g. 8A, Vilnius',
                'general_location' => 'Bernardine Garden · Old Town',
                'latitude' => 54.6849,
                'longitude' => 25.2951,
                'map_x' => 66,
                'map_y' => 36,
                'coordinate_accuracy' => 'Main public entrance',
                'distance_km' => 1.6,
                'travel_minutes' => 8,
                'open_state' => 'closing-soon',
                'open_label' => 'Closes at 10:00 PM',
                'closes_at' => '10:00 PM',
                'hours_summary' => 'Daily 7:00 AM–10:00 PM',
                'special_hours' => 'Seasonal closing time may change.',
                'phone' => null,
                'website' => 'https://vilnius.lt/',
                'email' => null,
                'accepted_species' => ['dog'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Leash required throughout the garden',
                'fenced' => false,
                'water' => false,
                'lighting' => true,
                'quiet_zone' => false,
                'parking' => false,
                'wheelchair_access' => true,
                'price_level' => 'free',
                'crowd_level' => 'high',
                'crowd_label' => 'Often busy with families and cyclists before sunset',
                'noise_level' => 'Moderate to busy',
                'rules' => [
                    'Pets stay on leash.',
                    'Keep away from planted beds and playground entrances.',
                    'Bring drinking water for your pet.',
                ],
                'features' => ['lighting', 'smooth paths', 'benches', 'bins', 'public transport'],
                'accessibility' => ['step-free main paths', 'frequent benches', 'nearby bus stops'],
                'safety' => ['good path visibility', 'staffed during opening hours'],
                'services' => ['1.3 km garden loop', 'rest areas', 'nearby pet-friendly cafes'],
                'pricing' => ['Park access' => 'Free'],
                'rating' => 4.5,
                'review_count' => 129,
                'verified_review_count' => 44,
                'verification' => [
                    'label' => 'Official location',
                    'scope' => 'Address and opening hours',
                    'updated_at' => '2026-07-25',
                    'tone' => 'verified',
                ],
                'data_freshness' => 'Hours checked 5 days ago',
                'recommendation_reason' => 'Closest well-lit option, but bring water and expect more people',
                'sponsored' => false,
                'allow_events' => false,
                'owner_managed' => false,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Formal city garden with broad paved walking paths',
                'events' => [],
                'base_warnings' => [],
            ],
            'pavilniai-calm-trail' => [
                'key' => 'pavilniai-calm-trail',
                'name' => 'Pavilniai calm forest trail',
                'short_name' => 'Pavilniai Trail',
                'primary_category' => 'park',
                'categories' => ['park', 'route'],
                'category_label' => 'Forest park and route',
                'category_icon' => 'trees',
                'summary' => 'The quietest option with wide forest sections and shade, though it is farther away and less consistently lit.',
                'city' => 'Vilnius',
                'neighborhood' => 'Pavilniai',
                'address' => 'Belmonto g., Vilnius',
                'general_location' => 'Pavilniai Regional Park · Belmontas side',
                'latitude' => 54.6817,
                'longitude' => 25.3577,
                'map_x' => 84,
                'map_y' => 48,
                'coordinate_accuracy' => 'General trail entrance',
                'distance_km' => 7.4,
                'travel_minutes' => 22,
                'open_state' => 'open',
                'open_label' => 'Open now',
                'closes_at' => 'Natural area',
                'hours_summary' => 'Open access; daylight visits recommended',
                'special_hours' => 'Trails may close during storms or maintenance.',
                'phone' => null,
                'website' => 'https://saugoma.lt/',
                'email' => null,
                'accepted_species' => ['dog'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Leash required around wildlife and shared paths',
                'fenced' => false,
                'water' => true,
                'lighting' => false,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => false,
                'price_level' => 'free',
                'crowd_level' => 'low',
                'crowd_label' => 'Usually quiet outside weekend afternoons',
                'noise_level' => 'Low',
                'rules' => [
                    'Keep pets controlled near wildlife.',
                    'Stay on marked trails.',
                    'Carry water and a charged phone.',
                ],
                'features' => ['forest shade', 'natural water', 'quiet paths', 'parking', 'shortcut loop'],
                'accessibility' => ['uneven natural surface', 'limited step-free access'],
                'safety' => ['mobile reception varies', 'unlit after dusk', 'seasonal tick activity'],
                'services' => ['5.2 km forest loop', '2.8 km shortcut', 'viewpoints'],
                'pricing' => ['Trail access' => 'Free'],
                'rating' => 4.8,
                'review_count' => 76,
                'verified_review_count' => 23,
                'verification' => [
                    'label' => 'Community mapped',
                    'scope' => 'Trail entrance and conditions',
                    'updated_at' => '2026-07-29',
                    'tone' => 'community',
                ],
                'data_freshness' => 'Trail conditions checked yesterday',
                'recommendation_reason' => 'Calmest match with shade and water, but farther and unlit',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => false,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Quiet forest path beneath tall green trees',
                'route' => [
                    'distance' => '5.2 km',
                    'duration' => '80–100 min',
                    'difficulty' => 'Moderate',
                    'surface' => 'Forest soil, roots, and compact gravel',
                    'elevation' => 'Several short climbs',
                    'shortcuts' => ['2.8 km lower loop', 'turnaround viewpoint at 1.7 km'],
                    'hazards' => ['ticks', 'mud after rain', 'limited lighting', 'variable mobile signal'],
                    'home_privacy' => 'The shared route starts at a public trail entrance.',
                ],
                'events' => [],
                'base_warnings' => [
                    [
                        'key' => 'pavilniai-ticks',
                        'title' => 'Seasonal tick activity',
                        'category' => 'parasites',
                        'status' => 'official-source',
                        'detail' => 'Check pets after leaving tall grass and forest edges.',
                        'reported_at' => '2026-07-28T09:00:00+03:00',
                        'expires_at' => '2026-09-30T23:59:00+03:00',
                        'confirmations' => 12,
                        'source' => 'Seasonal public guidance',
                    ],
                ],
            ],
            'zverynas-small-dog-run' => [
                'key' => 'zverynas-small-dog-run',
                'name' => 'Žvėrynas neighborhood dog run',
                'short_name' => 'Žvėrynas Dog Run',
                'primary_category' => 'dog-park',
                'categories' => ['dog-park'],
                'category_label' => 'Fenced dog park',
                'category_icon' => 'fence',
                'summary' => 'A free fenced run with separate small-dog space, double gate, water, and a temporary latch warning.',
                'city' => 'Vilnius',
                'neighborhood' => 'Žvėrynas',
                'address' => 'Birutės g. green area, Vilnius',
                'general_location' => 'Žvėrynas · Birutės Street green area',
                'latitude' => 54.6952,
                'longitude' => 25.2474,
                'map_x' => 43,
                'map_y' => 28,
                'coordinate_accuracy' => 'Community-confirmed entrance',
                'distance_km' => 2.7,
                'travel_minutes' => 11,
                'open_state' => 'open-with-warning',
                'open_label' => 'Open · active warning',
                'closes_at' => '10:00 PM',
                'hours_summary' => 'Daily 7:00 AM–10:00 PM',
                'special_hours' => 'Lighting is limited after 9:00 PM.',
                'phone' => null,
                'website' => null,
                'email' => null,
                'accepted_species' => ['dog'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Off leash inside the signed fenced zones',
                'fenced' => true,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => false,
                'wheelchair_access' => true,
                'price_level' => 'free',
                'crowd_level' => 'low',
                'crowd_label' => 'A few dogs reported 35 minutes ago',
                'noise_level' => 'Usually calm before workdays',
                'rules' => [
                    'Use the zone that matches your dog’s size and comfort.',
                    'Keep the entrance clear and close both gates.',
                    'Remove food if it creates tension.',
                ],
                'features' => ['fully fenced', 'double gate', 'small-dog zone', 'quiet zone', 'water', 'benches'],
                'accessibility' => ['step-free entrance', 'firm surface to the small-dog zone'],
                'safety' => ['1.5 m fence', 'double gate', 'separate size zones'],
                'services' => ['small-dog zone', 'general run', 'training corner', 'water point'],
                'pricing' => ['General access' => 'Free'],
                'rating' => 4.4,
                'review_count' => 58,
                'verified_review_count' => 19,
                'verification' => [
                    'label' => 'Community verified',
                    'scope' => 'Entrance, fence, zones and water',
                    'updated_at' => '2026-07-30',
                    'tone' => 'community',
                ],
                'data_freshness' => 'Entrance status checked 3 hours ago',
                'recommendation_reason' => 'Matches a small dog, double-gate, water and quiet-zone search',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => false,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Small dog standing on grass inside a fenced exercise area',
                'events' => [],
                'base_warnings' => [
                    [
                        'key' => 'zverynas-gate-latch',
                        'title' => 'Small-dog gate latch is loose',
                        'category' => 'damaged-fence',
                        'status' => 'confirmed',
                        'detail' => 'Hold the inner latch closed while another person enters.',
                        'reported_at' => '2026-07-30T08:15:00+03:00',
                        'expires_at' => '2026-08-02T08:15:00+03:00',
                        'confirmations' => 4,
                        'source' => 'Visitor photo and community confirmations',
                    ],
                ],
            ],
            'naujininkai-secure-dog-field' => [
                'key' => 'naujininkai-secure-dog-field',
                'name' => 'Naujininkai secure dog field',
                'short_name' => 'Naujininkai Dog Field',
                'primary_category' => 'dog-park',
                'categories' => ['dog-park'],
                'category_label' => 'Fenced dog park',
                'category_icon' => 'fence',
                'summary' => 'A quieter fully fenced field with double gates, separate zones, working water, and no active hazards.',
                'city' => 'Vilnius',
                'neighborhood' => 'Naujininkai',
                'address' => 'Dzūkų g. green area, Vilnius',
                'general_location' => 'Naujininkai · Dzūkų Street',
                'latitude' => 54.6595,
                'longitude' => 25.2782,
                'map_x' => 58,
                'map_y' => 73,
                'coordinate_accuracy' => 'Community-confirmed entrance',
                'distance_km' => 4.9,
                'travel_minutes' => 17,
                'open_state' => 'open',
                'open_label' => 'Open now',
                'closes_at' => '9:00 PM',
                'hours_summary' => 'Daily 7:00 AM–9:00 PM',
                'special_hours' => 'Water may be turned off during freezing weather.',
                'phone' => null,
                'website' => null,
                'email' => null,
                'accepted_species' => ['dog'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Off leash inside closed zones',
                'fenced' => true,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'free',
                'crowd_level' => 'low',
                'crowd_label' => 'Usually quiet; no recent crowd report',
                'noise_level' => 'Low to moderate',
                'rules' => [
                    'Use separate size zones.',
                    'Close both gates before removing the leash.',
                    'Take toys away if another dog guards them.',
                ],
                'features' => ['fully fenced', 'double gate', 'small-dog zone', 'water', 'lighting', 'parking'],
                'accessibility' => ['step-free entrance', 'firm central path', 'nearby parking'],
                'safety' => ['1.7 m fence', 'double gate', 'no active warnings'],
                'services' => ['small-dog zone', 'large-dog zone', 'training equipment', 'water point'],
                'pricing' => ['General access' => 'Free'],
                'rating' => 4.6,
                'review_count' => 34,
                'verified_review_count' => 14,
                'verification' => [
                    'label' => 'Community verified',
                    'scope' => 'Fence, entrances, zones and facilities',
                    'updated_at' => '2026-07-29',
                    'tone' => 'community',
                ],
                'data_freshness' => 'No hazards reported in the last 7 days',
                'recommendation_reason' => 'Safer current alternative with the same small-dog features',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => false,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Dogs standing in a spacious grassy fenced field',
                'events' => ['small-dog-social'],
                'base_warnings' => [],
            ],
            'paws-24-veterinary-center' => [
                'key' => 'paws-24-veterinary-center',
                'name' => 'Paws 24 Veterinary Center',
                'short_name' => 'Paws 24',
                'primary_category' => 'emergency-vet',
                'categories' => ['vet', 'emergency-vet', 'pet-store'],
                'category_label' => '24-hour veterinary center',
                'category_icon' => 'siren',
                'summary' => 'A fictional demo emergency clinic accepting birds and companion animals, with overnight diagnostics and an on-site clinician.',
                'city' => 'Vilnius',
                'neighborhood' => 'Šnipiškės',
                'address' => 'Demo address · Konstitucijos pr., Vilnius',
                'general_location' => 'Šnipiškės · Konstitucijos Avenue',
                'latitude' => 54.7015,
                'longitude' => 25.2685,
                'map_x' => 51,
                'map_y' => 21,
                'coordinate_accuracy' => 'Demo business entrance',
                'distance_km' => 2.2,
                'travel_minutes' => 9,
                'open_state' => 'open',
                'open_label' => 'Open 24 hours',
                'closes_at' => 'Open all night',
                'hours_summary' => 'Emergency reception 24/7; call before travel',
                'special_hours' => 'Overnight diagnostics and surgery depend on the on-call team.',
                'phone' => '+370 600 00024',
                'website' => null,
                'email' => 'demo-emergency@pawcircle.example',
                'accepted_species' => $allCompanions,
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Dogs leashed; cats, birds and small pets in secure carriers',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'paid',
                'crowd_level' => 'medium',
                'crowd_label' => 'Approximate wait: call for current triage status',
                'noise_level' => 'Separate quiet waiting area available',
                'rules' => [
                    'Call before travel when possible.',
                    'Use a secure carrier for birds and small animals.',
                    'Emergency cases are triaged by clinical need.',
                ],
                'features' => ['24-hour clinician', 'overnight diagnostics', 'surgery', 'inpatient care', 'separate waiting'],
                'accessibility' => ['step-free entrance', 'accessible parking', 'wide doors', 'wait in car option'],
                'safety' => ['separate dog and cat waiting', 'isolation room', 'on-site inpatient team'],
                'services' => ['emergency triage', 'x-ray', 'ultrasound', 'laboratory', 'surgery', 'avian care', 'inpatient care'],
                'pricing' => ['Emergency assessment' => 'From €65', 'Night surcharge' => 'Shown before treatment'],
                'rating' => 4.6,
                'review_count' => 92,
                'verified_review_count' => 37,
                'verification' => [
                    'label' => 'Demo business profile',
                    'scope' => 'Prototype contact, hours and species data',
                    'updated_at' => '2026-07-30',
                    'tone' => 'demo',
                ],
                'data_freshness' => 'Emergency hours confirmed in demo data today',
                'recommendation_reason' => 'Open now, accepts birds, and is the fastest suitable emergency option',
                'sponsored' => false,
                'allow_events' => false,
                'owner_managed' => true,
                'emergency' => true,
                'image' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Veterinary clinician examining a dog in a bright treatment room',
                'events' => ['travel-ready-webinar'],
                'base_warnings' => [],
            ],
            'night-paw-clinic' => [
                'key' => 'night-paw-clinic',
                'name' => 'Night Paw Veterinary Clinic',
                'short_name' => 'Night Paw Clinic',
                'primary_category' => 'emergency-vet',
                'categories' => ['vet', 'emergency-vet'],
                'category_label' => 'Overnight veterinary clinic',
                'category_icon' => 'siren',
                'summary' => 'A fictional demo overnight clinic for dogs and cats; it does not accept birds or exotic pets.',
                'city' => 'Vilnius',
                'neighborhood' => 'Naujamiestis',
                'address' => 'Demo address · Švitrigailos g., Vilnius',
                'general_location' => 'Naujamiestis · Švitrigailos Street',
                'latitude' => 54.6714,
                'longitude' => 25.2684,
                'map_x' => 50,
                'map_y' => 58,
                'coordinate_accuracy' => 'Demo business entrance',
                'distance_km' => 1.9,
                'travel_minutes' => 7,
                'open_state' => 'on-call',
                'open_label' => 'Emergency intake by phone',
                'closes_at' => 'On-call overnight',
                'hours_summary' => '8:00 PM–8:00 AM; phone confirmation required',
                'special_hours' => 'Only dogs and cats are accepted overnight.',
                'phone' => '+370 600 00091',
                'website' => null,
                'email' => 'demo-night@pawcircle.example',
                'accepted_species' => $commonPets,
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Dogs leashed; cats in secure carriers',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => false,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'paid',
                'crowd_level' => 'unknown',
                'crowd_label' => 'No current wait information',
                'noise_level' => 'Shared waiting area',
                'rules' => ['Call before travel.', 'Birds and exotic pets are not accepted.', 'Emergency cases are triaged.'],
                'features' => ['overnight intake', 'x-ray', 'laboratory', 'surgery on call'],
                'accessibility' => ['step-free entrance', 'parking close to entrance'],
                'safety' => ['secure carrier required for cats'],
                'services' => ['emergency triage', 'x-ray', 'laboratory', 'basic surgery'],
                'pricing' => ['Night assessment' => 'From €55'],
                'rating' => 4.2,
                'review_count' => 47,
                'verified_review_count' => 15,
                'verification' => [
                    'label' => 'Demo contact confirmed',
                    'scope' => 'Prototype hours and accepted species',
                    'updated_at' => '2026-07-29',
                    'tone' => 'demo',
                ],
                'data_freshness' => 'On-call schedule checked yesterday',
                'recommendation_reason' => 'Closer, but unsuitable for birds and requires phone confirmation',
                'sponsored' => false,
                'allow_events' => false,
                'owner_managed' => true,
                'emergency' => true,
                'image' => 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Dog waiting calmly in a veterinary reception area',
                'events' => [],
                'base_warnings' => [],
            ],
            'green-paw-neighborhood-clinic' => [
                'key' => 'green-paw-neighborhood-clinic',
                'name' => 'Green Paw Neighborhood Clinic',
                'short_name' => 'Green Paw Clinic',
                'primary_category' => 'vet',
                'categories' => ['vet'],
                'category_label' => 'Veterinary clinic',
                'category_icon' => 'stethoscope',
                'summary' => 'A fictional demo daytime clinic with online-request boundary, separate waiting spaces, and clear price ranges.',
                'city' => 'Vilnius',
                'neighborhood' => 'Antakalnis',
                'address' => 'Demo address · Antakalnio g., Vilnius',
                'general_location' => 'Antakalnis · near the clinic district',
                'latitude' => 54.7068,
                'longitude' => 25.3147,
                'map_x' => 72,
                'map_y' => 18,
                'coordinate_accuracy' => 'Demo business entrance',
                'distance_km' => 4.4,
                'travel_minutes' => 16,
                'open_state' => 'closed',
                'open_label' => 'Closed · opens 8:00 AM',
                'closes_at' => 'Opens 8:00 AM',
                'hours_summary' => 'Mon–Fri 8:00 AM–8:00 PM; Sat 9:00 AM–3:00 PM',
                'special_hours' => 'Appointments are recommended.',
                'phone' => '+370 600 00118',
                'website' => null,
                'email' => 'demo-clinic@pawcircle.example',
                'accepted_species' => ['dog', 'cat', 'rabbit', 'rodent'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Dogs leashed; other pets in secure carriers',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'paid',
                'crowd_level' => 'low',
                'crowd_label' => 'Appointments reduce waiting; live availability is not connected',
                'noise_level' => 'Separate cat waiting room',
                'rules' => ['Book or call before arrival.', 'Bring only selected documents.', 'Use a secure carrier when appropriate.'],
                'features' => ['separate waiting', 'rehabilitation', 'laboratory', 'dentistry', 'parking'],
                'accessibility' => ['step-free entrance', 'wide doors', 'accessible parking', 'wait in car option'],
                'safety' => ['separate dog and cat waiting', 'isolation room'],
                'services' => ['consultation', 'vaccination', 'laboratory', 'ultrasound', 'dentistry', 'rehabilitation'],
                'pricing' => ['Consultation' => '€35–€55', 'Ultrasound' => 'From €45'],
                'rating' => 4.8,
                'review_count' => 66,
                'verified_review_count' => 31,
                'verification' => [
                    'label' => 'Demo business profile',
                    'scope' => 'Prototype address, hours and services',
                    'updated_at' => '2026-07-28',
                    'tone' => 'demo',
                ],
                'data_freshness' => 'Services checked 2 days ago',
                'recommendation_reason' => 'Highly rated daytime option with a quiet waiting area',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => true,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Veterinary professional listening to a dog with a stethoscope',
                'events' => ['travel-ready-webinar'],
                'base_warnings' => [],
            ],
            'quiet-whiskers-grooming' => [
                'key' => 'quiet-whiskers-grooming',
                'name' => 'Quiet Whiskers Grooming Studio',
                'short_name' => 'Quiet Whiskers',
                'primary_category' => 'grooming',
                'categories' => ['grooming'],
                'category_label' => 'Low-stress grooming studio',
                'category_icon' => 'scissors',
                'summary' => 'A fictional individual-appointment studio for cats and dogs, with quiet drying, breaks, and private care notes.',
                'city' => 'Vilnius',
                'neighborhood' => 'Žirmūnai',
                'address' => 'Demo address · Žirmūnų g., Vilnius',
                'general_location' => 'Žirmūnai · near the river',
                'latitude' => 54.7182,
                'longitude' => 25.3014,
                'map_x' => 66,
                'map_y' => 10,
                'coordinate_accuracy' => 'Demo business entrance',
                'distance_km' => 4.1,
                'travel_minutes' => 15,
                'open_state' => 'open',
                'open_label' => 'Open · next demo slot Thu',
                'closes_at' => '7:00 PM',
                'hours_summary' => 'Tue–Sat 9:00 AM–7:00 PM; individual appointments',
                'special_hours' => 'Quiet cat appointments are held before noon.',
                'phone' => '+370 600 00207',
                'website' => null,
                'email' => 'demo-grooming@pawcircle.example',
                'accepted_species' => ['dog', 'cat', 'rabbit'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Dogs leashed; cats and rabbits in secure carriers',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'paid',
                'crowd_level' => 'low',
                'crowd_label' => 'One family at a time',
                'noise_level' => 'Quiet-dryer and no-force drying options',
                'rules' => ['Share handling concerns privately.', 'Public before-and-after photos require separate consent.', 'Breaks are available.'],
                'features' => ['cat grooming', 'quiet dryer', 'individual appointments', 'breaks', 'senior-pet handling'],
                'accessibility' => ['step-free entrance', 'parking nearby', 'seated handover area'],
                'safety' => ['one family at a time', 'private handling notes', 'owner can remain by agreement'],
                'services' => ['cat grooming', 'bath and brush', 'nail care', 'de-shedding', 'quiet drying', 'senior-pet care'],
                'pricing' => ['Cat grooming' => 'From €45', 'Quiet-dry session' => 'From €55'],
                'rating' => 4.9,
                'review_count' => 41,
                'verified_review_count' => 29,
                'verification' => [
                    'label' => 'Demo specialist profile',
                    'scope' => 'Prototype identity, services and studio access',
                    'updated_at' => '2026-07-29',
                    'tone' => 'demo',
                ],
                'data_freshness' => 'Demo availability updated yesterday',
                'recommendation_reason' => 'Works with cats, offers quiet drying, and schedules one family at a time',
                'sponsored' => false,
                'allow_events' => false,
                'owner_managed' => true,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Calm cat resting on a grooming table beside soft towels',
                'events' => [],
                'base_warnings' => [],
            ],
            'old-town-pet-cafe' => [
                'key' => 'old-town-pet-cafe',
                'name' => 'Courtyard Paws Cafe',
                'short_name' => 'Courtyard Paws',
                'primary_category' => 'pet-cafe',
                'categories' => ['pet-cafe'],
                'category_label' => 'Pet-friendly cafe',
                'category_icon' => 'coffee',
                'summary' => 'A fictional quiet-hours cafe where pets are currently allowed on the terrace only.',
                'city' => 'Vilnius',
                'neighborhood' => 'Old Town',
                'address' => 'Demo address · Pilies g., Vilnius',
                'general_location' => 'Old Town · Pilies Street courtyard',
                'latitude' => 54.6812,
                'longitude' => 25.2894,
                'map_x' => 63,
                'map_y' => 48,
                'coordinate_accuracy' => 'Demo business entrance',
                'distance_km' => 1.3,
                'travel_minutes' => 7,
                'open_state' => 'open',
                'open_label' => 'Open · terrace until 9:00 PM',
                'closes_at' => '9:00 PM',
                'hours_summary' => 'Daily 8:00 AM–9:00 PM',
                'special_hours' => 'Pets are terrace-only after the rule change on July 30.',
                'phone' => '+370 600 00316',
                'website' => null,
                'email' => 'demo-cafe@pawcircle.example',
                'accepted_species' => ['dog', 'cat'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Leash or secure carrier required',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => false,
                'wheelchair_access' => true,
                'price_level' => 'paid',
                'crowd_level' => 'low',
                'crowd_label' => 'Quietest 8:00–10:00 AM and after 7:30 PM',
                'noise_level' => 'Low during marked quiet hours',
                'rules' => ['Pets are allowed on the terrace only.', 'Keep pets on leash or in a carrier.', 'Do not feed unfamiliar pets.'],
                'features' => ['terrace', 'water bowls', 'quiet hours', 'step-free courtyard'],
                'accessibility' => ['step-free terrace', 'accessible restroom nearby', 'seating with aisle space'],
                'safety' => ['separate corner tables', 'no pet food presented as veterinary diet'],
                'services' => ['table service', 'water bowls', 'pet treats with ingredients shown'],
                'pricing' => ['Pet water' => 'Free', 'Pet treat plate' => '€4'],
                'rating' => 4.5,
                'review_count' => 73,
                'verified_review_count' => 26,
                'verification' => [
                    'label' => 'Owner-confirmed rule',
                    'scope' => 'Pet access, hours and terrace policy',
                    'updated_at' => '2026-07-30',
                    'tone' => 'verified',
                ],
                'data_freshness' => 'Pet-access rule corrected today',
                'recommendation_reason' => 'Quiet terrace with water close to the city center',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => true,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Quiet cafe terrace with tables beneath a covered courtyard',
                'events' => [],
                'base_warnings' => [],
            ],
            'city-pet-market' => [
                'key' => 'city-pet-market',
                'name' => 'City Pet Market and Pharmacy',
                'short_name' => 'City Pet Market',
                'primary_category' => 'pet-store',
                'categories' => ['pet-store'],
                'category_label' => 'Pet store',
                'category_icon' => 'shopping-bag',
                'summary' => 'A fictional pet shop with pickup, donation point, veterinary diets, and no live-animal sales.',
                'city' => 'Vilnius',
                'neighborhood' => 'Naujamiestis',
                'address' => 'Demo address · Kauno g., Vilnius',
                'general_location' => 'Naujamiestis · Kauno Street',
                'latitude' => 54.6744,
                'longitude' => 25.2749,
                'map_x' => 53,
                'map_y' => 55,
                'coordinate_accuracy' => 'Demo business entrance',
                'distance_km' => 1.8,
                'travel_minutes' => 8,
                'open_state' => 'open',
                'open_label' => 'Open until 8:00 PM',
                'closes_at' => '8:00 PM',
                'hours_summary' => 'Mon–Sat 9:00 AM–8:00 PM; Sun 10:00 AM–6:00 PM',
                'special_hours' => 'Inventory is not connected live; call before travel.',
                'phone' => '+370 600 00425',
                'website' => null,
                'email' => 'demo-store@pawcircle.example',
                'accepted_species' => $allCompanions,
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Leashed pets and secure carriers welcome',
                'fenced' => false,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => false,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'paid',
                'crowd_level' => 'medium',
                'crowd_label' => 'Usually quieter on weekday mornings',
                'noise_level' => 'Typical retail environment',
                'rules' => ['Leash or secure carrier required.', 'Prescription products require appropriate verification.', 'Live stock is not guaranteed.'],
                'features' => ['pickup counter', 'donation point', 'packaging recycling', 'no live-animal sales'],
                'accessibility' => ['step-free entrance', 'wide aisles', 'accessible parking'],
                'safety' => ['staffed pickup desk', 'prescription boundary'],
                'services' => ['food', 'veterinary diets', 'carriers', 'mobility aids', 'GPS collars', 'donation collection'],
                'pricing' => ['Pickup reservation' => 'No fee'],
                'rating' => 4.4,
                'review_count' => 88,
                'verified_review_count' => 33,
                'verification' => [
                    'label' => 'Demo business profile',
                    'scope' => 'Prototype hours and service categories',
                    'updated_at' => '2026-07-27',
                    'tone' => 'demo',
                ],
                'data_freshness' => 'Hours checked 3 days ago; inventory not live',
                'recommendation_reason' => 'Accessible pickup and a shelter donation point nearby',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => true,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Pet care products arranged on bright retail shelving',
                'events' => [],
                'base_warnings' => [],
            ],
            'vilnius-animal-aid' => [
                'key' => 'vilnius-animal-aid',
                'name' => 'Vilnius Animal Aid Center',
                'short_name' => 'Animal Aid Center',
                'primary_category' => 'shelter',
                'categories' => ['shelter'],
                'category_label' => 'Shelter and adoption center',
                'category_icon' => 'house-heart',
                'summary' => 'A fictional verified shelter profile with scheduled visits, fostering, donations, volunteer events, and microchip help.',
                'city' => 'Vilnius',
                'neighborhood' => 'Naujoji Vilnia',
                'address' => 'Demo address · Parko g., Vilnius',
                'general_location' => 'Naujoji Vilnia · Parko Street',
                'latitude' => 54.6947,
                'longitude' => 25.4166,
                'map_x' => 92,
                'map_y' => 31,
                'coordinate_accuracy' => 'Demo visitor entrance',
                'distance_km' => 11.8,
                'travel_minutes' => 29,
                'open_state' => 'appointment-only',
                'open_label' => 'Visits by appointment',
                'closes_at' => 'Office closes 6:00 PM',
                'hours_summary' => 'Visitor appointments Tue–Sun 11:00 AM–6:00 PM',
                'special_hours' => 'Do not bring resident pets unless the shelter confirms an introduction.',
                'phone' => '+370 600 00534',
                'website' => null,
                'email' => 'demo-shelter@pawcircle.example',
                'accepted_species' => ['dog', 'cat', 'rabbit', 'rodent'],
                'accepted_sizes' => $dogSizes,
                'leash_policy' => 'Resident pets only by approved appointment',
                'fenced' => true,
                'water' => true,
                'lighting' => true,
                'quiet_zone' => true,
                'parking' => true,
                'wheelchair_access' => true,
                'price_level' => 'free',
                'crowd_level' => 'low',
                'crowd_label' => 'Timed visits keep introductions calm',
                'noise_level' => 'Quiet introduction rooms available',
                'rules' => ['Book before visiting.', 'Do not bring a resident pet without approval.', 'Photography follows animal and visitor consent.'],
                'features' => ['adoption rooms', 'volunteer desk', 'donation point', 'foster coordination', 'microchip checks'],
                'accessibility' => ['step-free visitor entrance', 'accessible parking', 'seated meeting room'],
                'safety' => ['controlled introductions', 'separate species areas', 'staff escort'],
                'services' => ['adoption', 'fostering', 'volunteering', 'donations', 'microchip checks', 'transport coordination'],
                'pricing' => ['Visitor appointment' => 'Free', 'Donations' => 'Voluntary'],
                'rating' => 4.8,
                'review_count' => 52,
                'verified_review_count' => 28,
                'verification' => [
                    'label' => 'Demo organization profile',
                    'scope' => 'Prototype identity, visits and services',
                    'updated_at' => '2026-07-29',
                    'tone' => 'demo',
                ],
                'data_freshness' => 'Visitor rules checked yesterday',
                'recommendation_reason' => 'Verified volunteer and adoption programs with accessible visits',
                'sponsored' => false,
                'allow_events' => true,
                'owner_managed' => true,
                'emergency' => false,
                'image' => 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1600&h=1000&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1200&h=750&q=82',
                'image_alt' => 'Volunteer sitting calmly with a shelter dog outdoors',
                'events' => ['shelter-open-house'],
                'base_warnings' => [],
            ],
        ];
    }
}
