<?php

namespace App\Services;

final class PawCircleEventCatalog
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public function all(): array
    {
        return array_values($this->records());
    }

    /**
     * @return array<string, mixed>|null
     */
    public function find(string $key): ?array
    {
        return $this->records()[$key] ?? null;
    }

    /**
     * @return array{target: string, label: string, route: string, route_parameters: array<string, string>}|null
     */
    public function reportContext(string $target): ?array
    {
        $event = $this->find($target);

        if ($event === null) {
            return null;
        }

        return [
            'target' => $target,
            'label' => $event['title'],
            'route' => 'pet-social.meetups.show',
            'route_parameters' => ['event' => $target],
        ];
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    private function records(): array
    {
        return [
            'small-dog-social' => [
                'key' => 'small-dog-social',
                'title' => 'Calm walk at Laurelhurst Park',
                'short_description' => 'A host-guided parallel walk with calm arrivals and no off-leash play.',
                'description' => 'A low-pressure neighborhood walk for medium and larger dogs who do best with space. We begin with parallel movement, keep every dog on leash, and share the exact meeting point only with approved attendees.',
                'category' => 'Walk',
                'event_type' => 'group-walk',
                'format' => 'offline',
                'privacy' => 'closed',
                'registration_policy' => 'approval',
                'status' => 'registration_open',
                'starts_at' => '2026-08-01T10:00:00-07:00',
                'ends_at' => '2026-08-01T11:30:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Laurelhurst Park · Southeast Portland',
                'exact_location' => 'SE Ankeny entrance beside the covered picnic tables',
                'online_link' => null,
                'distance' => '1.2 mi',
                'capacity' => 8,
                'base_attendees' => 6,
                'waitlist_count' => 1,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => 'Medium or large dogs · leash required · calm introductions',
                'activity_level' => 'Calm',
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => 'Mia Carter',
                'organizer_type' => 'Owner',
                'organizer_initials' => 'MC',
                'verification_label' => null,
                'managed_by_current_user' => true,
                'language' => 'English',
                'image' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Two dogs walking side by side on a tree-lined path',
                'tags' => ['parallel walk', 'calm pace', 'leash required'],
                'recommendation_reason' => 'Matches Scout’s size and your interest in calm local walks',
                'commercial_label' => null,
                'weather' => [
                    'summary' => 'Mild with light cloud',
                    'temperature' => '68°F',
                    'advisory' => 'Bring individual water and expect damp grass.',
                    'tone' => 'safe',
                ],
            ],
            'puppy-social-lab' => [
                'key' => 'puppy-social-lab',
                'title' => 'Puppy socialization lab',
                'short_description' => 'Small supervised groups, breaks, and careful first experiences.',
                'description' => 'A practical socialization session for young dogs with structured observation, short exercises, and rest. One meeting cannot complete socialization, so the trainer will focus on safe routines owners can continue at home.',
                'category' => 'Training',
                'event_type' => 'puppy-training',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'approval',
                'status' => 'few_spots',
                'starts_at' => '2026-08-02T09:30:00-07:00',
                'ends_at' => '2026-08-02T10:30:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Rose City Training Hall · Buckman',
                'exact_location' => 'Studio B, 815 SE Belmont Street',
                'online_link' => null,
                'distance' => '2.4 mi',
                'capacity' => 6,
                'base_attendees' => 5,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => 'Puppies 12–24 weeks · vaccination status reviewed privately',
                'activity_level' => 'Moderate',
                'ticket_model' => 'paid',
                'price_minor' => 3500,
                'currency' => 'USD',
                'organizer' => 'Ari Jensen',
                'organizer_type' => 'Verified trainer',
                'organizer_initials' => 'AJ',
                'verification_label' => 'Professional qualification verified',
                'managed_by_current_user' => false,
                'language' => 'English',
                'image' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Young golden retriever sitting outside during a training break',
                'tags' => ['puppies', 'trainer led', 'small group'],
                'recommendation_reason' => 'A verified trainer near your saved neighborhood',
                'commercial_label' => 'Paid event',
                'weather' => [
                    'summary' => 'Indoor event',
                    'temperature' => 'Climate controlled',
                    'advisory' => 'Arrive ten minutes early for a calm entry.',
                    'tone' => 'safe',
                ],
            ],
            'beginner-training-series' => [
                'key' => 'beginner-training-series',
                'title' => 'Foundations training course',
                'short_description' => 'Four beginner sessions covering attention, recall, waiting, and leash skills.',
                'description' => 'A four-session foundation course with one check-in per class, take-home material, and an owner chat. Attendance confirms participation only and does not grant a professional qualification.',
                'category' => 'Training',
                'event_type' => 'training-course',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-08T11:00:00-07:00',
                'ends_at' => '2026-08-08T12:15:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Sellwood Community Hall',
                'exact_location' => 'Room 204, 1436 SE Spokane Street',
                'online_link' => null,
                'distance' => '3.1 mi',
                'capacity' => 6,
                'base_attendees' => 3,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => 'Beginner dogs · fixed leash · one responsible handler',
                'activity_level' => 'Moderate',
                'ticket_model' => 'paid',
                'price_minor' => 12000,
                'currency' => 'USD',
                'organizer' => 'Ari Jensen',
                'organizer_type' => 'Verified trainer',
                'organizer_initials' => 'AJ',
                'verification_label' => 'Professional qualification verified',
                'managed_by_current_user' => false,
                'language' => 'English',
                'image' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Dog looking toward a handler during a focused training session',
                'tags' => ['beginner course', 'four sessions', 'materials included'],
                'recommendation_reason' => 'You saved beginner training posts recently',
                'commercial_label' => 'Paid course',
                'weather' => [
                    'summary' => 'Indoor event',
                    'temperature' => 'Climate controlled',
                    'advisory' => 'A quiet waiting area is available near the side entrance.',
                    'tone' => 'safe',
                ],
            ],
            'rose-city-pet-show' => [
                'key' => 'rose-city-pet-show',
                'title' => 'Rose City companion show',
                'short_description' => 'Verified show schedule, categories, document guidance, and quiet zones.',
                'description' => 'A club-run companion show with category schedules, veterinary control, accessible seating, quiet preparation areas, and individual QR check-in.',
                'category' => 'Show',
                'event_type' => 'pet-show',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'approval',
                'status' => 'registration_open',
                'starts_at' => '2026-08-15T08:00:00-07:00',
                'ends_at' => '2026-08-15T18:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Portland Expo Center',
                'exact_location' => 'Hall D, exhibitor entrance on Marine Drive',
                'online_link' => null,
                'distance' => '7.8 mi',
                'capacity' => 120,
                'base_attendees' => 82,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 2,
                'pet_requirements' => 'Registered category and privately reviewed documents',
                'activity_level' => 'Variable',
                'ticket_model' => 'paid',
                'price_minor' => 4500,
                'currency' => 'USD',
                'organizer' => 'Rose City Companion Club',
                'organizer_type' => 'Verified organization',
                'organizer_initials' => 'RC',
                'verification_label' => 'Organization and venue verified',
                'managed_by_current_user' => false,
                'language' => 'English + Spanish',
                'image' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Dog standing calmly at a public companion event',
                'tags' => ['show', 'verified venue', 'quiet zone'],
                'recommendation_reason' => 'A verified event followed by your local groups',
                'commercial_label' => 'Paid event',
                'weather' => [
                    'summary' => 'Indoor event',
                    'temperature' => 'Climate controlled',
                    'advisory' => 'Use the exhibitor entrance shown after approval.',
                    'tone' => 'safe',
                ],
            ],
            'shelter-open-house' => [
                'key' => 'shelter-open-house',
                'title' => 'Shelter open house and adoption day',
                'short_description' => 'Meet adoptable pets, learn about fostering, and tour the shelter safely.',
                'description' => 'A verified shelter day with timed introductions, volunteer orientation, supply collection, and clear rules about bringing resident pets.',
                'category' => 'Adoption',
                'event_type' => 'adoption-day',
                'format' => 'offline',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-09T12:00:00-07:00',
                'ends_at' => '2026-08-09T16:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Rose City Animal Aid · North Portland',
                'exact_location' => 'Visitor entrance, 2050 N Columbia Boulevard',
                'online_link' => null,
                'distance' => '5.6 mi',
                'capacity' => 60,
                'base_attendees' => 34,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => 'Owners attend without resident pets',
                'activity_level' => 'Easy',
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => 'Rose City Animal Aid',
                'organizer_type' => 'Verified shelter',
                'organizer_initials' => 'RA',
                'verification_label' => 'Shelter verified',
                'managed_by_current_user' => false,
                'language' => 'English + Spanish',
                'image' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1605484649538-98578113d4f1?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Shelter dog resting safely on a blue couch',
                'tags' => ['adoption', 'fostering', 'without resident pets'],
                'recommendation_reason' => 'You follow local adoption and foster topics',
                'commercial_label' => null,
                'weather' => [
                    'summary' => 'Mostly indoors',
                    'temperature' => '70°F',
                    'advisory' => 'The tour includes a short covered outdoor section.',
                    'tone' => 'safe',
                ],
            ],
            'missing-scout-search' => [
                'key' => 'missing-scout-search',
                'title' => 'Urgent neighborhood search for Scout',
                'short_description' => 'Coordinated volunteer search with assigned zones and safe sighting instructions.',
                'description' => 'A time-sensitive search action. Volunteers receive a public meeting point, a zone, and instructions not to chase or publicly share private resident details.',
                'category' => 'Search action',
                'event_type' => 'search-action',
                'format' => 'offline',
                'privacy' => 'closed',
                'registration_policy' => 'approval',
                'status' => 'urgent',
                'starts_at' => '2026-07-30T18:00:00-07:00',
                'ends_at' => '2026-07-30T21:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Alberta Arts District',
                'exact_location' => 'Volunteer desk at Alberta Park west entrance',
                'online_link' => null,
                'distance' => '2.0 mi',
                'capacity' => 40,
                'base_attendees' => 22,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => 'Volunteers attend without pets',
                'activity_level' => 'Moderate',
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => 'Mia Carter',
                'organizer_type' => 'Owner and search coordinator',
                'organizer_initials' => 'MC',
                'verification_label' => 'Lost-pet alert confirmed',
                'managed_by_current_user' => true,
                'language' => 'English',
                'image' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Brown dog looking toward the camera in a grassy area',
                'tags' => ['urgent', 'volunteers', 'do not chase'],
                'recommendation_reason' => 'Urgent verified alert in your nearby area',
                'commercial_label' => null,
                'weather' => [
                    'summary' => 'Clear evening',
                    'temperature' => '65°F',
                    'advisory' => 'Bring a charged phone and reflective outer layer.',
                    'tone' => 'attention',
                ],
            ],
            'baxter-birthday' => [
                'key' => 'baxter-birthday',
                'title' => 'Baxter’s quiet birthday picnic',
                'short_description' => 'A private celebration for close pet friends and their owners.',
                'description' => 'A small invitation-only picnic with a quiet rest zone, pre-agreed food rules, and a private shared album after the event.',
                'category' => 'Celebration',
                'event_type' => 'private-celebration',
                'format' => 'offline',
                'privacy' => 'hidden',
                'registration_policy' => 'invitation',
                'status' => 'registration_open',
                'starts_at' => '2026-08-16T15:00:00-07:00',
                'ends_at' => '2026-08-16T17:00:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Private garden · Portland',
                'exact_location' => 'Shared only with accepted guests',
                'online_link' => null,
                'distance' => 'Private',
                'capacity' => 10,
                'base_attendees' => 7,
                'waitlist_count' => 0,
                'pets_allowed' => true,
                'pet_limit' => 1,
                'pet_requirements' => 'Invited pet friends only · food agreed in advance',
                'activity_level' => 'Calm',
                'ticket_model' => 'free',
                'price_minor' => 0,
                'currency' => 'USD',
                'organizer' => 'Jamie Cho',
                'organizer_type' => 'Owner',
                'organizer_initials' => 'JC',
                'verification_label' => null,
                'managed_by_current_user' => false,
                'language' => 'English',
                'image' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Dog wearing a birthday hat at a small celebration',
                'tags' => ['private', 'quiet zone', 'friends only'],
                'recommendation_reason' => 'Invited through Scout’s close pet circle',
                'commercial_label' => null,
                'weather' => [
                    'summary' => 'Warm afternoon',
                    'temperature' => '74°F',
                    'advisory' => 'Shade and a quiet indoor room are available.',
                    'tone' => 'safe',
                ],
            ],
            'travel-ready-webinar' => [
                'key' => 'travel-ready-webinar',
                'title' => 'Travel-ready pet webinar',
                'short_description' => 'Verified veterinary guidance for carriers, documents, routines, and travel planning.',
                'description' => 'A live webinar with moderated questions, timezone-aware reminders, protected access, captions, a recording, slides, and cited resources. The presenter does not diagnose individual pets during the stream.',
                'category' => 'Webinar',
                'event_type' => 'expert-webinar',
                'format' => 'online',
                'privacy' => 'public',
                'registration_policy' => 'instant',
                'status' => 'registration_open',
                'starts_at' => '2026-08-06T18:00:00-07:00',
                'ends_at' => '2026-08-06T19:15:00-07:00',
                'timezone' => 'America/Los_Angeles',
                'general_location' => 'Online',
                'exact_location' => 'Online room opens 15 minutes before the webinar',
                'online_link' => 'https://events.example.test/travel-ready',
                'distance' => 'Online',
                'capacity' => 250,
                'base_attendees' => 146,
                'waitlist_count' => 0,
                'pets_allowed' => false,
                'pet_limit' => 0,
                'pet_requirements' => 'Owners may attend without pets',
                'activity_level' => 'Lecture',
                'ticket_model' => 'paid',
                'price_minor' => 1800,
                'currency' => 'USD',
                'organizer' => 'Dr. Elena Park',
                'organizer_type' => 'Verified veterinarian',
                'organizer_initials' => 'EP',
                'verification_label' => 'Veterinary profession verified',
                'managed_by_current_user' => false,
                'language' => 'English · captions available',
                'image' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1600&h=900&q=85',
                'image_small' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=720&h=540&q=80',
                'image_medium' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1200&h=675&q=82',
                'thumbnail' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=240&h=240&q=80',
                'image_alt' => 'Veterinarian speaking with a pet owner beside a dog',
                'tags' => ['online', 'veterinarian', 'recording included'],
                'recommendation_reason' => 'You saved travel planning guides for Scout',
                'commercial_label' => 'Paid webinar',
                'weather' => [
                    'summary' => 'Online event',
                    'temperature' => 'Join from home',
                    'advisory' => 'Test audio and captions before the room opens.',
                    'tone' => 'safe',
                ],
            ],
        ];
    }
}
