<x-detail-page
    :owner="$owner"
    :title="$share['copy']['page']['title']"
    :active-section="$share['item']['active_section']"
    section="share-hub"
    :back-href="$share['item']['url']"
    :back-label="$share['copy']['page']['back']"
    data-share-page
>
    <x-slot:hero>
        <x-context-hero :context="$share['item']" section="share-context">
            <x-slot:actions>
                <x-action-control
                    :href="$share['item']['url']"
                    :label="$share['copy']['page']['open']"
                    icon="external-link"
                    variant="paper"
                    size="regular"
                    data-share-open-original
                />
            </x-slot:actions>
        </x-context-hero>
    </x-slot:hero>

    <x-slot:main>
        <x-content-panel
            section="share-channels"
            :eyebrow="$share['copy']['channels']['eyebrow']"
            :title="$share['copy']['channels']['title']"
            :meta="$share['copy']['channels']['count']"
            data-share-channels-panel
        >
            <x-share-channel-grid
                :channels="$share['channels']"
                :empty-title="$share['copy']['channels']['empty_title']"
                :empty="$share['copy']['channels']['empty_description']"
                class="section-body"
            />
        </x-content-panel>

        <x-content-panel
            section="share-neighbors"
            :eyebrow="$share['copy']['neighbors']['eyebrow']"
            :title="$share['copy']['neighbors']['title']"
            :meta="$share['copy']['neighbors']['count']"
            data-share-neighbors-panel
        >
            <x-share-recipient-list
                :recipients="$share['recipients']"
                :empty-title="$share['copy']['neighbors']['empty_title']"
                :empty="$share['copy']['neighbors']['empty_description']"
                class="section-body"
            />
        </x-content-panel>
    </x-slot:main>

    <x-slot:sidebar>
        <x-content-panel
            section="share-link-details"
            :title="$share['copy']['details']['title']"
            data-share-details
        >
            <x-definition-list
                :items="$share['linkDetails']"
                :empty="$share['copy']['details']['empty']"
                strong
                class="section-body"
            />
        </x-content-panel>

        <x-notice
            section="share-privacy"
            icon="shield-check"
            :title="$share['copy']['privacy']['title']"
            :description="$share['copy']['privacy']['description']"
            data-share-privacy
        />
    </x-slot:sidebar>
</x-detail-page>
