<?php

declare(strict_types=1);

return [
    'password.request' => 'tests/Feature/Auth/AuthenticationTest.php',
    'password.reset' => 'tests/Feature/Auth/AuthenticationTest.php',
    'circle.index' => 'tests/Feature/PreviewTest.php',
    'connections.index' => 'tests/Feature/PreviewTest.php',
    'pet-friends.index' => 'tests/Feature/PreviewTest.php',
    'messages.details' => 'tests/Feature/PreviewTest.php',
    'messages.actions' => 'tests/Feature/PreviewTest.php',
    'walks.index' => 'tests/Feature/PreviewTest.php',
    'notifications.index' => 'tests/Feature/PreviewTest.php',
    'organizations.index' => 'tests/Feature/Organizations/OrganizationAuthorityFoundationTest.php',
    'organizations.invitations.respond' => 'tests/Feature/Organizations/OrganizationAuthorityFoundationTest.php',
    'organizations.show' => 'tests/Feature/Organizations/OrganizationAuthorityFoundationTest.php',
    'compose' => 'tests/Feature/PreviewTest.php',
    'discover.index' => 'tests/Feature/PreviewTest.php',
    'groups.apartment_pets' => 'tests/Feature/GroupDirectoryPreviewTest.php',
    'groups.created' => 'tests/Feature/GroupDirectoryPreviewTest.php',
    'groups.show' => 'tests/Feature/GroupDirectoryPreviewTest.php',
    'meetups.small_dog_social' => 'tests/Feature/MeetupDirectoryPreviewTest.php',
    'meetups.created' => 'tests/Feature/MeetupDirectoryPreviewTest.php',
    'meetups.show' => 'tests/Feature/MeetupDirectoryPreviewTest.php',
    'members.show' => 'tests/Feature/DiscoverExperienceTest.php',
    'forum.topics.edit' => 'tests/Feature/ForumTopicTest.php',
    'forum.topics.update' => 'tests/Feature/ForumTopicTest.php',
    'forum.topics.destroy' => 'tests/Feature/ForumTopicTest.php',
    'neighbors.index' => 'tests/Feature/PreviewTest.php',
    'neighbors.ari' => 'tests/Feature/PreviewTest.php',
    'pets.nori' => 'tests/Feature/PetProfilePreviewTest.php',
    'posts.show' => 'tests/Feature/PreviewTest.php',
    'profile.mia' => 'tests/Feature/PetProfilePreviewTest.php',
    'share.show' => 'tests/Feature/PreviewTest.php',
    'experts.create' => 'tests/Feature/ExpertDirectoryTest.php',
    'experts.edit' => 'tests/Feature/ExpertDirectoryTest.php',
    'experts.update' => 'tests/Feature/ExpertDirectoryTest.php',
    'experts.actions' => 'tests/Feature/ExpertSafetyTest.php',
    'care-journals.tasks.store' => 'tests/Feature/CareJournalTest.php',
    'care-journals.routines.store' => 'tests/Feature/CareJournalTest.php',
    'devices.create' => 'tests/Feature/SmartDeviceTest.php',
    'devices.events.acknowledge' => 'tests/Feature/SmartDeviceTest.php',
    'medical-access.show' => 'tests/Feature/MedicalRecordTest.php',
    'medical-access.documents.download' => 'tests/Feature/MedicalRecordTest.php',
    'device-access.show' => 'tests/Feature/SmartDeviceTest.php',
];
