<?php

declare(strict_types=1);

return [
    'deletion_grace_days' => 30,
    'manager_invitation_days' => 14,
    'species_options' => [
        'dog',
        'cat',
        'bird',
        'rabbit',
        'rodent',
        'fish',
        'reptile',
        'amphibian',
        'horse',
        'farm-animal',
        'exotic',
        'unknown',
        'other',
    ],
    'versioned_fact_keys' => [
        'name',
        'birth-date',
        'breed',
        'sex',
        'reproductive-status',
        'microchip-status',
        'microchip-identifier',
        'registration-identifier',
        'identifying-mark',
        'body-measurement',
    ],
    'fact_source_types' => [
        'owner',
        'shelter',
        'clinic',
        'document',
        'microchip-registry',
        'genetic-test',
        'specialist',
        'device',
        'estimate',
        'unknown',
    ],
    'fact_precisions' => [
        'exact',
        'estimated',
        'month',
        'year',
        'range',
        'unknown',
    ],
    'allowed_section_privacy_keys' => [
        'basics',
        'media',
        'owners',
        'friends',
        'location',
        'events',
        'achievements',
        'documents',
        'adoption',
        'memorial',
        'microchip-status',
        'special-needs',
        'posts',
        'care',
        'activity',
    ],
];
