<?php

declare(strict_types=1);

return [
    'deletion_grace_days' => 30,
    'manager_invitation_days' => 14,
    'species_options' => [
        'dog',
        'cat',
        'bird',
        'rabbit',
        'rodent',
        'fish',
        'reptile',
        'amphibian',
        'horse',
        'farm-animal',
        'exotic',
        'unknown',
        'other',
    ],
    'life_stage_threshold_months' => [
        'dog' => ['newborn' => 0, 'juvenile' => 2, 'young' => 6, 'adult' => 24, 'senior' => 84],
        'cat' => ['newborn' => 0, 'juvenile' => 2, 'young' => 6, 'adult' => 24, 'senior' => 120],
        'bird' => ['newborn' => 0, 'juvenile' => 1, 'young' => 6, 'adult' => 18, 'senior' => 120],
        'rabbit' => ['newborn' => 0, 'juvenile' => 1, 'young' => 3, 'adult' => 6, 'senior' => 60],
        'rodent' => ['newborn' => 0, 'juvenile' => 1, 'young' => 2, 'adult' => 4, 'senior' => 18],
        'fish' => ['newborn' => 0, 'juvenile' => 1, 'young' => 3, 'adult' => 12, 'senior' => 60],
        'reptile' => ['newborn' => 0, 'juvenile' => 1, 'young' => 12, 'adult' => 36, 'senior' => 180],
        'horse' => ['newborn' => 0, 'juvenile' => 1, 'young' => 12, 'adult' => 48, 'senior' => 180],
    ],
    'versioned_fact_keys' => [
        'name',
        'birth-date',
        'breed',
        'sex',
        'reproductive-status',
        'microchip-status',
        'microchip-identifier',
        'microchip-record',
        'registration-identifier',
        'identifying-mark',
        'body-measurement',
    ],
    'fact_source_types' => [
        'owner',
        'shelter',
        'clinic',
        'document',
        'microchip-registry',
        'genetic-test',
        'specialist',
        'device',
        'estimate',
        'unknown',
    ],
    'fact_precisions' => [
        'exact',
        'estimated',
        'month',
        'year',
        'range',
        'unknown',
    ],
    'allowed_section_privacy_keys' => [
        'basics',
        'media',
        'owners',
        'friends',
        'location',
        'events',
        'achievements',
        'documents',
        'adoption',
        'memorial',
        'microchip-status',
        'special-needs',
        'posts',
        'care',
        'activity',
    ],
];
