<?php

declare(strict_types=1);

/**
 * Generate factory and seeder coverage for every first-party Eloquent model.
 *
 * Usage:
 * php scripts/generate-seeding-coverage.php
 * php scripts/generate-seeding-coverage.php --write
 * php scripts/generate-seeding-coverage.php --check
 */
$root = dirname(__DIR__);
$outputPath = $root.'/docs/seeding-coverage.md';
$arguments = array_slice($argv, 1);
$supportedArguments = ['--check', '--write'];
$unknownArguments = array_values(array_diff($arguments, $supportedArguments));
$checkOnly = in_array('--check', $arguments, true);
$write = in_array('--write', $arguments, true);

if ($unknownArguments !== []) {
    fwrite(STDERR, 'Unknown argument(s): '.implode(', ', $unknownArguments).".\n");
    exit(1);
}

if ($checkOnly && $write) {
    fwrite(STDERR, "Use either --check or --write, not both.\n");
    exit(1);
}

$modelFiles = glob($root.'/app/Models/*.php') ?: [];
$seederFiles = glob($root.'/database/seeders/*Seeder.php') ?: [];
$representativeModels = representativeModels(
    $root.'/database/seeders/RepresentativeModelManifest.php',
);
$rows = [];
$stateCount = 0;
$missingFactoryCount = 0;

sort($modelFiles);

foreach ($modelFiles as $modelFile) {
    $model = pathinfo($modelFile, PATHINFO_FILENAME);
    $factoryRelativePath = "database/factories/{$model}Factory.php";
    $factoryPath = $root.'/'.$factoryRelativePath;
    $factoryExists = is_file($factoryPath);
    $missingFactoryCount += $factoryExists ? 0 : 1;
    $states = $factoryExists ? factoryStates($factoryPath) : [];
    $seeders = modelSeeders($model, $seederFiles);

    if (isset($representativeModels[$model]) && $model !== 'User') {
        $seeders[] = 'RepresentativeDomainSeeder';
        $seeders = array_values(array_unique($seeders));
        sort($seeders);
    }

    $stateCount += count($states);
    $stateSummary = $states === [] ? [] : array_map(
        static fn (string $state): string => "`{$state}()`",
        $states,
    );

    $rows[] = [
        'model' => $model,
        'factory' => $factoryExists ? "`{$factoryRelativePath}`" : 'Missing',
        'states' => $stateSummary === [] ? 'Default state only' : implode(', ', $stateSummary),
        'referenceSeeder' => referenceSeeder($seeders),
        'demoSeeder' => $seeders === [] ? 'Not directly seeded' : implode(', ', array_map(
            static fn (string $seeder): string => "`{$seeder}`",
            $seeders,
        )),
        'fixture' => 'Factory-generated local data',
        'tests' => '`tests/Feature/Database/FactoryAndSeederTest.php`',
        'exemption' => $factoryExists ? 'None' : 'Undocumented exemption',
    ];
}

$contents = "# Seeding Coverage Matrix\n\n";
$contents .= 'Generated by `php scripts/generate-seeding-coverage.php --write`; ';
$contents .= 'verify exact byte parity with `php scripts/generate-seeding-coverage.php --check`. ';
$contents .= 'The matrix inventories every first-party model and fails the release gate when a ';
$contents .= "factory is missing without a documented exemption.\n\n";
$contents .= 'Models: **'.count($rows)."**. Explicit factory state/helper methods: **{$stateCount}**.\n\n";
$contents .= "| Model | Factory | States / helpers | Reference seeder | Demo seeder | Fixture | Test | Exemption |\n";
$contents .= "| --- | --- | --- | --- | --- | --- | --- | --- |\n";

foreach ($rows as $row) {
    $contents .= '| '.implode(' | ', array_map('escape', $row))." |\n";
}

$contents .= "\n## Rules\n\n";
$contents .= "- A default factory creates a valid, constraint-compliant record.\n";
$contents .= "- Helpers create only intentional graph relationships; large graphs are opt-in.\n";
$contents .= "- Fixed reference seeders are idempotent and use stable natural keys.\n";
$contents .= "- Demo seeding is environment-gated and never truncates existing data.\n";
$contents .= "- Internet access is prohibited during factory and seeder execution.\n";

if ($missingFactoryCount > 0) {
    fwrite(STDERR, "{$missingFactoryCount} first-party model factories are missing.\n");
    exit(1);
}

if ($checkOnly) {
    if (! is_file($outputPath) || file_get_contents($outputPath) !== $contents) {
        fwrite(STDERR, "{$outputPath} is stale. Regenerate it with --write.\n");
        exit(1);
    }

    fwrite(STDOUT, sprintf(
        "Verified seeding coverage for %d models and %d explicit helpers.\n",
        count($rows),
        $stateCount,
    ));
    exit(0);
}

if ($write) {
    writeGeneratedFile($outputPath, $contents);
    fwrite(STDOUT, sprintf(
        "Generated seeding coverage for %d models and %d explicit helpers.\n",
        count($rows),
        $stateCount,
    ));
    exit(0);
}

fwrite(STDOUT, $contents);

/**
 * @return list<string>
 */
function factoryStates(string $factoryPath): array
{
    $contents = file_get_contents($factoryPath);

    if ($contents === false) {
        return [];
    }

    preg_match_all('/public function ([A-Za-z][A-Za-z0-9_]*)\s*\(/', $contents, $matches);

    $excluded = ['configure', 'definition'];
    $states = array_values(array_filter(
        array_unique($matches[1]),
        static fn (string $method): bool => ! in_array($method, $excluded, true),
    ));
    sort($states);

    return $states;
}

/**
 * @param  list<string>  $seederFiles
 * @return list<string>
 */
function modelSeeders(string $model, array $seederFiles): array
{
    $seeders = [];

    foreach ($seederFiles as $seederFile) {
        $contents = file_get_contents($seederFile);

        if ($contents === false
            || ! preg_match('/\b'.preg_quote($model, '/').'(?:::|;|\s)/', $contents)) {
            continue;
        }

        $seeders[] = pathinfo($seederFile, PATHINFO_FILENAME);
    }

    sort($seeders);

    return $seeders;
}

/** @return array<string, true> */
function representativeModels(string $manifestPath): array
{
    $contents = is_file($manifestPath) ? file_get_contents($manifestPath) : false;

    if ($contents === false) {
        return [];
    }

    preg_match_all('/\b([A-Za-z][A-Za-z0-9_]*)::class\b/', $contents, $matches);

    return array_fill_keys(array_unique($matches[1]), true);
}

/**
 * @param  list<string>  $seeders
 */
function referenceSeeder(array $seeders): string
{
    $references = array_values(array_filter(
        $seeders,
        static fn (string $seeder): bool => str_contains($seeder, 'Reference')
            || str_contains($seeder, 'Role')
            || str_contains($seeder, 'Permission'),
    ));

    if ($references === []) {
        return 'Not applicable';
    }

    return implode(', ', array_map(
        static fn (string $seeder): string => "`{$seeder}`",
        $references,
    ));
}

function escape(string $value): string
{
    return str_replace('|', '\\|', $value);
}

function writeGeneratedFile(string $outputPath, string $contents): void
{
    $directory = dirname($outputPath);

    if (! is_dir($directory)) {
        fwrite(STDERR, "Output directory {$directory} does not exist.\n");
        exit(1);
    }

    $temporaryPath = tempnam($directory, '.seeding-coverage.');

    if ($temporaryPath === false) {
        fwrite(STDERR, "Unable to create a temporary file in {$directory}.\n");
        exit(1);
    }

    $written = file_put_contents($temporaryPath, $contents, LOCK_EX) !== false;
    $permissionsSet = $written && chmod($temporaryPath, 0644);
    $replaced = $permissionsSet && rename($temporaryPath, $outputPath);

    if (is_file($temporaryPath)) {
        unlink($temporaryPath);
    }

    if (! $written) {
        fwrite(STDERR, "Unable to write temporary coverage file {$temporaryPath}.\n");
        exit(1);
    }

    if (! $permissionsSet) {
        fwrite(STDERR, "Unable to set permissions on {$temporaryPath}.\n");
        exit(1);
    }

    if (! $replaced) {
        fwrite(STDERR, "Unable to replace {$outputPath}.\n");
        exit(1);
    }
}
