<?php

declare(strict_types=1);

/**
 * Generate factory and seeder coverage for every first-party Eloquent model.
 *
 * Usage:
 * php scripts/generate-seeding-coverage.php > docs/seeding-coverage.md
 */
$root = dirname(__DIR__);
$modelFiles = glob($root.'/app/Models/*.php') ?: [];
$seederFiles = glob($root.'/database/seeders/*.php') ?: [];
$rows = [];
$stateCount = 0;
$enumStateCount = 0;

sort($modelFiles);

foreach ($modelFiles as $modelFile) {
    $model = pathinfo($modelFile, PATHINFO_FILENAME);
    $factoryRelativePath = "database/factories/{$model}Factory.php";
    $factoryPath = $root.'/'.$factoryRelativePath;
    $factoryExists = is_file($factoryPath);
    $states = $factoryExists ? factoryStates($factoryPath) : [];
    $enumStates = $factoryExists ? modelEnumStates($modelFile, $root) : [];
    $seeders = modelSeeders($model, $seederFiles);
    $stateCount += count($states);
    $enumStateCount += array_sum($enumStates);

    $stateSummary = $states === [] ? [] : array_map(
        static fn (string $state): string => "`{$state}()`",
        $states,
    );

    foreach ($enumStates as $attribute => $count) {
        $stateSummary[] = "`withEnum({$attribute})` ({$count})";
    }

    $rows[] = [
        'model' => $model,
        'factory' => $factoryExists ? "`{$factoryRelativePath}`" : 'Missing',
        'states' => $stateSummary === [] ? 'Default state only' : implode(', ', $stateSummary),
        'referenceSeeder' => referenceSeeder($seeders),
        'demoSeeder' => $seeders === [] ? 'Not directly seeded' : implode(', ', array_map(
            static fn (string $seeder): string => "`{$seeder}`",
            $seeders,
        )),
        'fixture' => 'Factory-generated local data',
        'tests' => '`tests/Feature/Database/FactoryAndSeederTest.php`',
        'exemption' => $factoryExists ? 'None' : 'Undocumented exemption',
    ];
}

echo "# Seeding Coverage Matrix\n\n";
echo 'Generated by `php scripts/generate-seeding-coverage.php`. ';
echo 'It inventories every first-party model and fails the release gate when a ';
echo "factory is missing without a documented exemption.\n\n";
echo 'Models: **'.count($rows)."**. Explicit factory state/helper methods: **{$stateCount}**. ";
echo "Verified enum-backed states: **{$enumStateCount}**.\n\n";
echo "| Model | Factory | States / helpers | Reference seeder | Demo seeder | Fixture | Test | Exemption |\n";
echo "| --- | --- | --- | --- | --- | --- | --- | --- |\n";

foreach ($rows as $row) {
    echo '| '.implode(' | ', array_map('escape', $row))." |\n";
}

echo "\n## Rules\n\n";
echo "- A default factory creates a valid, constraint-compliant record.\n";
echo "- Helpers create only intentional graph relationships; large graphs are opt-in.\n";
echo "- Fixed reference seeders are idempotent and use stable natural keys.\n";
echo "- Demo seeding is environment-gated and never truncates existing data.\n";
echo "- Internet access is prohibited during factory and seeder execution.\n";

/**
 * @return list<string>
 */
function factoryStates(string $factoryPath): array
{
    $contents = file_get_contents($factoryPath);

    if ($contents === false) {
        return [];
    }

    preg_match_all('/public function ([A-Za-z][A-Za-z0-9_]*)\s*\(/', $contents, $matches);

    $excluded = ['configure', 'definition'];
    $states = array_values(array_filter(
        array_unique($matches[1]),
        static fn (string $method): bool => ! in_array($method, $excluded, true),
    ));
    sort($states);

    return $states;
}

/**
 * @return array<string, int>
 */
function modelEnumStates(string $modelPath, string $root): array
{
    $contents = file_get_contents($modelPath);

    if ($contents === false) {
        return [];
    }

    preg_match_all('/use App\\\\Enums\\\\([A-Za-z][A-Za-z0-9_]*);/', $contents, $imports);
    $enumNames = array_fill_keys($imports[1], true);
    preg_match_all(
        "/'([A-Za-z][A-Za-z0-9_]*)'\\s*=>\\s*([A-Za-z][A-Za-z0-9_]*)::class/",
        $contents,
        $casts,
        PREG_SET_ORDER,
    );

    $states = [];

    foreach ($casts as $cast) {
        [$match, $attribute, $enumName] = $cast;
        unset($match);

        if (! isset($enumNames[$enumName])) {
            continue;
        }

        $enumPath = "{$root}/app/Enums/{$enumName}.php";
        $enumContents = is_file($enumPath) ? file_get_contents($enumPath) : false;

        if ($enumContents === false) {
            continue;
        }

        preg_match_all('/^\s*case\s+[A-Za-z][A-Za-z0-9_]*\s*=/m', $enumContents, $cases);
        $states[$attribute] = count($cases[0]);
    }

    ksort($states);

    return $states;
}

/**
 * @param  list<string>  $seederFiles
 * @return list<string>
 */
function modelSeeders(string $model, array $seederFiles): array
{
    $seeders = [];

    foreach ($seederFiles as $seederFile) {
        $contents = file_get_contents($seederFile);

        if ($contents === false
            || ! preg_match('/\b'.preg_quote($model, '/').'(?:::|;|\s)/', $contents)) {
            continue;
        }

        $seeders[] = pathinfo($seederFile, PATHINFO_FILENAME);
    }

    sort($seeders);

    return $seeders;
}

/**
 * @param  list<string>  $seeders
 */
function referenceSeeder(array $seeders): string
{
    $references = array_values(array_filter(
        $seeders,
        static fn (string $seeder): bool => str_contains($seeder, 'Reference')
            || str_contains($seeder, 'Role')
            || str_contains($seeder, 'Permission'),
    ));

    if ($references === []) {
        return 'Not applicable';
    }

    return implode(', ', array_map(
        static fn (string $seeder): string => "`{$seeder}`",
        $references,
    ));
}

function escape(string $value): string
{
    return str_replace('|', '\\|', $value);
}
